// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: web/v1/auth.proto

package web

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录接口请求参数
type AuthLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 登录账号（前端字段名仍为 mobile；服务端仅按 users.username 精确匹配）
	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 登录密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 登录平台
	Platform string `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	// 图形验证码凭证（与 AuthCaptchaResponse.voucher 对应；可在配置中关闭校验）
	CaptchaVoucher string `protobuf:"bytes,4,opt,name=captcha_voucher,json=captchaVoucher,proto3" json:"captcha_voucher,omitempty"`
	// 用户输入的图形验证码
	Captcha       string `protobuf:"bytes,5,opt,name=captcha,proto3" json:"captcha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLoginRequest) Reset() {
	*x = AuthLoginRequest{}
	mi := &file_web_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLoginRequest) ProtoMessage() {}

func (x *AuthLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLoginRequest.ProtoReflect.Descriptor instead.
func (*AuthLoginRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthLoginRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AuthLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthLoginRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AuthLoginRequest) GetCaptchaVoucher() string {
	if x != nil {
		return x.CaptchaVoucher
	}
	return ""
}

func (x *AuthLoginRequest) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

type AuthCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthCaptchaRequest) Reset() {
	*x = AuthCaptchaRequest{}
	mi := &file_web_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCaptchaRequest) ProtoMessage() {}

func (x *AuthCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCaptchaRequest.ProtoReflect.Descriptor instead.
func (*AuthCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{1}
}

type AuthCaptchaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 验证码唯一凭证，登录时放在 captcha_voucher（关闭验证码时为空）
	Voucher string `protobuf:"bytes,1,opt,name=voucher,proto3" json:"voucher,omitempty"`
	// PNG 图片 base64（不含 data:image 前缀；关闭验证码时为空）
	Captcha string `protobuf:"bytes,2,opt,name=captcha,proto3" json:"captcha,omitempty"`
	// 与 app.disable_login_captcha 一致：为 true 时登录无需传验证码，voucher/captcha 可忽略
	DisableLoginCaptcha bool `protobuf:"varint,3,opt,name=disable_login_captcha,json=disableLoginCaptcha,proto3" json:"disable_login_captcha,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthCaptchaResponse) Reset() {
	*x = AuthCaptchaResponse{}
	mi := &file_web_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCaptchaResponse) ProtoMessage() {}

func (x *AuthCaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCaptchaResponse.ProtoReflect.Descriptor instead.
func (*AuthCaptchaResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthCaptchaResponse) GetVoucher() string {
	if x != nil {
		return x.Voucher
	}
	return ""
}

func (x *AuthCaptchaResponse) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

func (x *AuthCaptchaResponse) GetDisableLoginCaptcha() bool {
	if x != nil {
		return x.DisableLoginCaptcha
	}
	return false
}

// 登录接口响应参数
type AuthLoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token 类型
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// token
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// 过期时间
	ExpiresIn int32 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	// 是否已设置交易密码（0/1）
	IsTrans       int32 `protobuf:"varint,4,opt,name=is_trans,json=isTrans,proto3" json:"is_trans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLoginResponse) Reset() {
	*x = AuthLoginResponse{}
	mi := &file_web_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLoginResponse) ProtoMessage() {}

func (x *AuthLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLoginResponse.ProtoReflect.Descriptor instead.
func (*AuthLoginResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthLoginResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AuthLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthLoginResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *AuthLoginResponse) GetIsTrans() int32 {
	if x != nil {
		return x.IsTrans
	}
	return 0
}

// 注册接口请求参数
type AuthRegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 昵称
	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 手机号（可选）
	Mobile string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	// 邮箱（可选）
	Email string `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	// 登录密码
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	// 登录平台
	Platform string `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	// 短信验证码（手机注册时需要）
	SmsCode string `protobuf:"bytes,5,opt,name=sms_code,json=smsCode,proto3" json:"sms_code,omitempty"`
	// 邀请码（可选）
	InviteCode string `protobuf:"bytes,6,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	// 邮箱验证码（邮箱注册时需要）
	EmailCode string `protobuf:"bytes,8,opt,name=email_code,json=emailCode,proto3" json:"email_code,omitempty"`
	// 设备码（配置开启 register_device_limit 时必填；最长 128）
	DeviceCode    string `protobuf:"bytes,9,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRegisterRequest) Reset() {
	*x = AuthRegisterRequest{}
	mi := &file_web_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRegisterRequest) ProtoMessage() {}

func (x *AuthRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRegisterRequest.ProtoReflect.Descriptor instead.
func (*AuthRegisterRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *AuthRegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AuthRegisterRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AuthRegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthRegisterRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AuthRegisterRequest) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

func (x *AuthRegisterRequest) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *AuthRegisterRequest) GetEmailCode() string {
	if x != nil {
		return x.EmailCode
	}
	return ""
}

func (x *AuthRegisterRequest) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

// 注册接口响应参数
type AuthRegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token 类型
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// token
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// 过期时间
	ExpiresIn     int32 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRegisterResponse) Reset() {
	*x = AuthRegisterResponse{}
	mi := &file_web_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRegisterResponse) ProtoMessage() {}

func (x *AuthRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRegisterResponse.ProtoReflect.Descriptor instead.
func (*AuthRegisterResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *AuthRegisterResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AuthRegisterResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthRegisterResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 退出登录接口请求参数
type AuthLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLogoutRequest) Reset() {
	*x = AuthLogoutRequest{}
	mi := &file_web_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLogoutRequest) ProtoMessage() {}

func (x *AuthLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLogoutRequest.ProtoReflect.Descriptor instead.
func (*AuthLogoutRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{6}
}

// 退出登录接口响应参数
type AuthLogoutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 提示信息
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLogoutResponse) Reset() {
	*x = AuthLogoutResponse{}
	mi := &file_web_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLogoutResponse) ProtoMessage() {}

func (x *AuthLogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLogoutResponse.ProtoReflect.Descriptor instead.
func (*AuthLogoutResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *AuthLogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthLogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Token 刷新接口请求参数
type AuthRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRefreshTokenRequest) Reset() {
	*x = AuthRefreshTokenRequest{}
	mi := &file_web_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRefreshTokenRequest) ProtoMessage() {}

func (x *AuthRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*AuthRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{8}
}

// Token 刷新接口响应参数
type AuthRefreshTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token 类型
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// token
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// 过期时间
	ExpiresIn     int32 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRefreshTokenResponse) Reset() {
	*x = AuthRefreshTokenResponse{}
	mi := &file_web_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRefreshTokenResponse) ProtoMessage() {}

func (x *AuthRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*AuthRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *AuthRefreshTokenResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AuthRefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthRefreshTokenResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 找回密码接口请求参数
type AuthForgetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 邮箱
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// 登录密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 邮箱验证码
	EmailCode     string `protobuf:"bytes,3,opt,name=email_code,json=emailCode,proto3" json:"email_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthForgetRequest) Reset() {
	*x = AuthForgetRequest{}
	mi := &file_web_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthForgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthForgetRequest) ProtoMessage() {}

func (x *AuthForgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthForgetRequest.ProtoReflect.Descriptor instead.
func (*AuthForgetRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *AuthForgetRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthForgetRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthForgetRequest) GetEmailCode() string {
	if x != nil {
		return x.EmailCode
	}
	return ""
}

// 找回密码接口响应参数
type AuthForgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthForgetResponse) Reset() {
	*x = AuthForgetResponse{}
	mi := &file_web_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthForgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthForgetResponse) ProtoMessage() {}

func (x *AuthForgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthForgetResponse.ProtoReflect.Descriptor instead.
func (*AuthForgetResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{11}
}

type AuthOauthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OauthType     string                 `protobuf:"bytes,3,opt,name=oauth_type,json=oauthType,proto3" json:"oauth_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthOauthRequest) Reset() {
	*x = AuthOauthRequest{}
	mi := &file_web_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOauthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOauthRequest) ProtoMessage() {}

func (x *AuthOauthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOauthRequest.ProtoReflect.Descriptor instead.
func (*AuthOauthRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *AuthOauthRequest) GetOauthType() string {
	if x != nil {
		return x.OauthType
	}
	return ""
}

type AuthOauthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthOauthResponse) Reset() {
	*x = AuthOauthResponse{}
	mi := &file_web_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOauthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOauthResponse) ProtoMessage() {}

func (x *AuthOauthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOauthResponse.ProtoReflect.Descriptor instead.
func (*AuthOauthResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *AuthOauthResponse) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type AuthOauthLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OauthType     string                 `protobuf:"bytes,3,opt,name=oauth_type,json=oauthType,proto3" json:"oauth_type,omitempty"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthOauthLoginRequest) Reset() {
	*x = AuthOauthLoginRequest{}
	mi := &file_web_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOauthLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOauthLoginRequest) ProtoMessage() {}

func (x *AuthOauthLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOauthLoginRequest.ProtoReflect.Descriptor instead.
func (*AuthOauthLoginRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *AuthOauthLoginRequest) GetOauthType() string {
	if x != nil {
		return x.OauthType
	}
	return ""
}

func (x *AuthOauthLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AuthOauthLoginRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type AuthOauthLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAuthorize   string                 `protobuf:"bytes,1,opt,name=is_authorize,json=isAuthorize,proto3" json:"is_authorize,omitempty"`
	Authorize     *Authorize             `protobuf:"bytes,2,opt,name=authorize,proto3" json:"authorize,omitempty"`
	BindToken     string                 `protobuf:"bytes,3,opt,name=bind_token,json=bindToken,proto3" json:"bind_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthOauthLoginResponse) Reset() {
	*x = AuthOauthLoginResponse{}
	mi := &file_web_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOauthLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOauthLoginResponse) ProtoMessage() {}

func (x *AuthOauthLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOauthLoginResponse.ProtoReflect.Descriptor instead.
func (*AuthOauthLoginResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *AuthOauthLoginResponse) GetIsAuthorize() string {
	if x != nil {
		return x.IsAuthorize
	}
	return ""
}

func (x *AuthOauthLoginResponse) GetAuthorize() *Authorize {
	if x != nil {
		return x.Authorize
	}
	return nil
}

func (x *AuthOauthLoginResponse) GetBindToken() string {
	if x != nil {
		return x.BindToken
	}
	return ""
}

type Authorize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authorize) Reset() {
	*x = Authorize{}
	mi := &file_web_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authorize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorize) ProtoMessage() {}

func (x *Authorize) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorize.ProtoReflect.Descriptor instead.
func (*Authorize) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *Authorize) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Authorize) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *Authorize) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AuthOAuthBindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BindToken     string                 `protobuf:"bytes,1,opt,name=bind_token,json=bindToken,proto3" json:"bind_token,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	SmsCode       string                 `protobuf:"bytes,3,opt,name=sms_code,json=smsCode,proto3" json:"sms_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthOAuthBindRequest) Reset() {
	*x = AuthOAuthBindRequest{}
	mi := &file_web_v1_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOAuthBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOAuthBindRequest) ProtoMessage() {}

func (x *AuthOAuthBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOAuthBindRequest.ProtoReflect.Descriptor instead.
func (*AuthOAuthBindRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{17}
}

func (x *AuthOAuthBindRequest) GetBindToken() string {
	if x != nil {
		return x.BindToken
	}
	return ""
}

func (x *AuthOAuthBindRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *AuthOAuthBindRequest) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

type AuthOAuthBindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authorize     *Authorize             `protobuf:"bytes,2,opt,name=authorize,proto3" json:"authorize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthOAuthBindResponse) Reset() {
	*x = AuthOAuthBindResponse{}
	mi := &file_web_v1_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthOAuthBindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthOAuthBindResponse) ProtoMessage() {}

func (x *AuthOAuthBindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthOAuthBindResponse.ProtoReflect.Descriptor instead.
func (*AuthOAuthBindResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{18}
}

func (x *AuthOAuthBindResponse) GetAuthorize() *Authorize {
	if x != nil {
		return x.Authorize
	}
	return nil
}

// 邮箱登录请求参数
type AuthEmailLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 邮箱
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// 邮箱验证码
	EmailCode string `protobuf:"bytes,2,opt,name=email_code,json=emailCode,proto3" json:"email_code,omitempty"`
	// 登录平台
	Platform      string `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthEmailLoginRequest) Reset() {
	*x = AuthEmailLoginRequest{}
	mi := &file_web_v1_auth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthEmailLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthEmailLoginRequest) ProtoMessage() {}

func (x *AuthEmailLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthEmailLoginRequest.ProtoReflect.Descriptor instead.
func (*AuthEmailLoginRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{19}
}

func (x *AuthEmailLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthEmailLoginRequest) GetEmailCode() string {
	if x != nil {
		return x.EmailCode
	}
	return ""
}

func (x *AuthEmailLoginRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// 邮箱登录响应参数
type AuthEmailLoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token 类型
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// token
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// 过期时间
	ExpiresIn     int32 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthEmailLoginResponse) Reset() {
	*x = AuthEmailLoginResponse{}
	mi := &file_web_v1_auth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthEmailLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthEmailLoginResponse) ProtoMessage() {}

func (x *AuthEmailLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthEmailLoginResponse.ProtoReflect.Descriptor instead.
func (*AuthEmailLoginResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{20}
}

func (x *AuthEmailLoginResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AuthEmailLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthEmailLoginResponse) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 注销账号请求参数
type AuthCancelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 邮箱验证码（发往当前账号绑定邮箱，渠道与 send-email 一致）
	EmailCode     string `protobuf:"bytes,1,opt,name=email_code,json=emailCode,proto3" json:"email_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthCancelRequest) Reset() {
	*x = AuthCancelRequest{}
	mi := &file_web_v1_auth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCancelRequest) ProtoMessage() {}

func (x *AuthCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCancelRequest.ProtoReflect.Descriptor instead.
func (*AuthCancelRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{21}
}

func (x *AuthCancelRequest) GetEmailCode() string {
	if x != nil {
		return x.EmailCode
	}
	return ""
}

// 注销账号响应参数
type AuthCancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthCancelResponse) Reset() {
	*x = AuthCancelResponse{}
	mi := &file_web_v1_auth_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCancelResponse) ProtoMessage() {}

func (x *AuthCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_auth_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCancelResponse.ProtoReflect.Descriptor instead.
func (*AuthCancelResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_auth_proto_rawDescGZIP(), []int{22}
}

var File_web_v1_auth_proto protoreflect.FileDescriptor

const file_web_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x11web/v1/auth.proto\x12\x03web\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xdd\x01\n" +
	"\x10AuthLoginRequest\x12#\n" +
	"\x06mobile\x18\x01 \x01(\tB\v\xe2A\x01\x02\xbaH\x04r\x02\x10\x01R\x06mobile\x12'\n" +
	"\bpassword\x18\x02 \x01(\tB\v\xe2A\x01\x02\xbaH\x04r\x02\x10\x01R\bpassword\x128\n" +
	"\bplatform\x18\x03 \x01(\tB\x1c\xe2A\x01\x02\xbaH\x15r\x13R\x03webR\awindowsR\x03macR\bplatform\x12'\n" +
	"\x0fcaptcha_voucher\x18\x04 \x01(\tR\x0ecaptchaVoucher\x12\x18\n" +
	"\acaptcha\x18\x05 \x01(\tR\acaptcha\"\x14\n" +
	"\x12AuthCaptchaRequest\"\x8f\x01\n" +
	"\x13AuthCaptchaResponse\x12\x1e\n" +
	"\avoucher\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\avoucher\x12\x1e\n" +
	"\acaptcha\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\acaptcha\x128\n" +
	"\x15disable_login_captcha\x18\x03 \x01(\bB\x04\xe2A\x01\x02R\x13disableLoginCaptcha\"\x9c\x01\n" +
	"\x11AuthLoginResponse\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04type\x12'\n" +
	"\faccess_token\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\vaccessToken\x12#\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05B\x04\xe2A\x01\x02R\texpiresIn\x12\x1f\n" +
	"\bis_trans\x18\x04 \x01(\x05B\x04\xe2A\x01\x02R\aisTrans\"\xcb\x02\n" +
	"\x13AuthRegisterRequest\x12%\n" +
	"\bnickname\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x18\x14R\bnickname\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bpassword\x124\n" +
	"\bplatform\x18\x04 \x01(\tB\x18\xbaH\x15r\x13R\x03webR\awindowsR\x03macR\bplatform\x12\x19\n" +
	"\bsms_code\x18\x05 \x01(\tR\asmsCode\x12\x1f\n" +
	"\vinvite_code\x18\x06 \x01(\tR\n" +
	"inviteCode\x12\x1d\n" +
	"\n" +
	"email_code\x18\b \x01(\tR\temailCode\x12)\n" +
	"\vdevice_code\x18\t \x01(\tB\b\xbaH\x05r\x03\x18\x80\x01R\n" +
	"deviceCode\"~\n" +
	"\x14AuthRegisterResponse\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04type\x12'\n" +
	"\faccess_token\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\vaccessToken\x12#\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05B\x04\xe2A\x01\x02R\texpiresIn\"\x13\n" +
	"\x11AuthLogoutRequest\"T\n" +
	"\x12AuthLogoutResponse\x12\x1e\n" +
	"\asuccess\x18\x01 \x01(\bB\x04\xe2A\x01\x02R\asuccess\x12\x1e\n" +
	"\amessage\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\amessage\"\x19\n" +
	"\x17AuthRefreshTokenRequest\"\x82\x01\n" +
	"\x18AuthRefreshTokenResponse\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04type\x12'\n" +
	"\faccess_token\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\vaccessToken\x12#\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05B\x04\xe2A\x01\x02R\texpiresIn\"\x8c\x01\n" +
	"\x11AuthForgetRequest\x12!\n" +
	"\x05email\x18\x01 \x01(\tB\v\xe2A\x01\x02\xbaH\x04r\x02`\x01R\x05email\x12'\n" +
	"\bpassword\x18\x02 \x01(\tB\v\xe2A\x01\x02\xbaH\x04r\x02\x10\x01R\bpassword\x12+\n" +
	"\n" +
	"email_code\x18\x03 \x01(\tB\f\xe2A\x01\x02\xbaH\x05r\x03\x98\x01\x06R\temailCode\"\x14\n" +
	"\x12AuthForgetResponse\"K\n" +
	"\x10AuthOauthRequest\x127\n" +
	"\n" +
	"oauth_type\x18\x03 \x01(\tB\x18\xe2A\x01\x02\xbaH\x11r\x0fR\x06githubR\x05giteeR\toauthType\"+\n" +
	"\x11AuthOauthResponse\x12\x16\n" +
	"\x03uri\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x03uri\"\x94\x01\n" +
	"\x15AuthOauthLoginRequest\x127\n" +
	"\n" +
	"oauth_type\x18\x03 \x01(\tB\x18\xe2A\x01\x02\xbaH\x11r\x0fR\x06githubR\x05giteeR\toauthType\x12\x1f\n" +
	"\x04code\x18\x01 \x01(\tB\v\xe2A\x01\x02\xbaH\x04r\x02\x10\x01R\x04code\x12!\n" +
	"\x05state\x18\x02 \x01(\tB\v\xe2A\x01\x02\xbaH\x04r\x02\x10\x01R\x05state\"\x9a\x01\n" +
	"\x16AuthOauthLoginResponse\x12'\n" +
	"\fis_authorize\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\visAuthorize\x122\n" +
	"\tauthorize\x18\x02 \x01(\v2\x0e.web.AuthorizeB\x04\xe2A\x01\x02R\tauthorize\x12#\n" +
	"\n" +
	"bind_token\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\tbindToken\"s\n" +
	"\tAuthorize\x12'\n" +
	"\faccess_token\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\vaccessToken\x12#\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\x05B\x04\xe2A\x01\x02R\texpiresIn\x12\x18\n" +
	"\x04type\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\x04type\"\x8f\x01\n" +
	"\x14AuthOAuthBindRequest\x12*\n" +
	"\n" +
	"bind_token\x18\x01 \x01(\tB\v\xe2A\x01\x02\xbaH\x04r\x02\x10\x01R\tbindToken\x12#\n" +
	"\x06mobile\x18\x02 \x01(\tB\v\xe2A\x01\x02\xbaH\x04r\x02\x10\x01R\x06mobile\x12&\n" +
	"\bsms_code\x18\x03 \x01(\tB\v\xe2A\x01\x02\xbaH\x04r\x02\x10\x01R\asmsCode\"K\n" +
	"\x15AuthOAuthBindResponse\x122\n" +
	"\tauthorize\x18\x02 \x01(\v2\x0e.web.AuthorizeB\x04\xe2A\x01\x02R\tauthorize\"\xa1\x01\n" +
	"\x15AuthEmailLoginRequest\x12!\n" +
	"\x05email\x18\x01 \x01(\tB\v\xe2A\x01\x02\xbaH\x04r\x02\x10\x01R\x05email\x12+\n" +
	"\n" +
	"email_code\x18\x02 \x01(\tB\f\xe2A\x01\x02\xbaH\x05r\x03\x98\x01\x06R\temailCode\x128\n" +
	"\bplatform\x18\x03 \x01(\tB\x1c\xe2A\x01\x02\xbaH\x15r\x13R\x03webR\awindowsR\x03macR\bplatform\"\x80\x01\n" +
	"\x16AuthEmailLoginResponse\x12\x18\n" +
	"\x04type\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04type\x12'\n" +
	"\faccess_token\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\vaccessToken\x12#\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05B\x04\xe2A\x01\x02R\texpiresIn\"@\n" +
	"\x11AuthCancelRequest\x12+\n" +
	"\n" +
	"email_code\x18\x01 \x01(\tB\f\xe2A\x01\x02\xbaH\x05r\x03\x98\x01\x06R\temailCode\"\x14\n" +
	"\x12AuthCancelResponse2\xbb\b\n" +
	"\x04Auth\x12U\n" +
	"\x05Login\x12\x15.web.AuthLoginRequest\x1a\x16.web.AuthLoginResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12]\n" +
	"\aCaptcha\x12\x17.web.AuthCaptchaRequest\x1a\x18.web.AuthCaptchaResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/captcha\x12a\n" +
	"\bRegister\x12\x18.web.AuthRegisterRequest\x1a\x19.web.AuthRegisterResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/register\x12Y\n" +
	"\x06Forget\x12\x16.web.AuthForgetRequest\x1a\x17.web.AuthForgetResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/auth/forget\x12U\n" +
	"\x05Oauth\x12\x15.web.AuthOauthRequest\x1a\x16.web.AuthOauthResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/oauth\x12f\n" +
	"\tOauthBind\x12\x19.web.AuthOAuthBindRequest\x1a\x1a.web.AuthOAuthBindResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/auth/oauth/bind\x12j\n" +
	"\n" +
	"OauthLogin\x12\x1a.web.AuthOauthLoginRequest\x1a\x1b.web.AuthOauthLoginResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/auth/oauth/login\x12j\n" +
	"\n" +
	"EmailLogin\x12\x1a.web.AuthEmailLoginRequest\x1a\x1b.web.AuthEmailLoginResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/auth/email-login\x12r\n" +
	"\fRefreshToken\x12\x1c.web.AuthRefreshTokenRequest\x1a\x1d.web.AuthRefreshTokenResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/auth/refresh-token\x12Y\n" +
	"\x06Logout\x12\x16.web.AuthLogoutRequest\x1a\x17.web.AuthLogoutResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/auth/logout\x12Y\n" +
	"\x06Cancel\x12\x16.web.AuthCancelRequest\x1a\x17.web.AuthCancelResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/auth/cancelB\fZ\n" +
	"web/v1;webb\x06proto3"

var (
	file_web_v1_auth_proto_rawDescOnce sync.Once
	file_web_v1_auth_proto_rawDescData []byte
)

func file_web_v1_auth_proto_rawDescGZIP() []byte {
	file_web_v1_auth_proto_rawDescOnce.Do(func() {
		file_web_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_v1_auth_proto_rawDesc), len(file_web_v1_auth_proto_rawDesc)))
	})
	return file_web_v1_auth_proto_rawDescData
}

var file_web_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_web_v1_auth_proto_goTypes = []any{
	(*AuthLoginRequest)(nil),         // 0: web.AuthLoginRequest
	(*AuthCaptchaRequest)(nil),       // 1: web.AuthCaptchaRequest
	(*AuthCaptchaResponse)(nil),      // 2: web.AuthCaptchaResponse
	(*AuthLoginResponse)(nil),        // 3: web.AuthLoginResponse
	(*AuthRegisterRequest)(nil),      // 4: web.AuthRegisterRequest
	(*AuthRegisterResponse)(nil),     // 5: web.AuthRegisterResponse
	(*AuthLogoutRequest)(nil),        // 6: web.AuthLogoutRequest
	(*AuthLogoutResponse)(nil),       // 7: web.AuthLogoutResponse
	(*AuthRefreshTokenRequest)(nil),  // 8: web.AuthRefreshTokenRequest
	(*AuthRefreshTokenResponse)(nil), // 9: web.AuthRefreshTokenResponse
	(*AuthForgetRequest)(nil),        // 10: web.AuthForgetRequest
	(*AuthForgetResponse)(nil),       // 11: web.AuthForgetResponse
	(*AuthOauthRequest)(nil),         // 12: web.AuthOauthRequest
	(*AuthOauthResponse)(nil),        // 13: web.AuthOauthResponse
	(*AuthOauthLoginRequest)(nil),    // 14: web.AuthOauthLoginRequest
	(*AuthOauthLoginResponse)(nil),   // 15: web.AuthOauthLoginResponse
	(*Authorize)(nil),                // 16: web.Authorize
	(*AuthOAuthBindRequest)(nil),     // 17: web.AuthOAuthBindRequest
	(*AuthOAuthBindResponse)(nil),    // 18: web.AuthOAuthBindResponse
	(*AuthEmailLoginRequest)(nil),    // 19: web.AuthEmailLoginRequest
	(*AuthEmailLoginResponse)(nil),   // 20: web.AuthEmailLoginResponse
	(*AuthCancelRequest)(nil),        // 21: web.AuthCancelRequest
	(*AuthCancelResponse)(nil),       // 22: web.AuthCancelResponse
}
var file_web_v1_auth_proto_depIdxs = []int32{
	16, // 0: web.AuthOauthLoginResponse.authorize:type_name -> web.Authorize
	16, // 1: web.AuthOAuthBindResponse.authorize:type_name -> web.Authorize
	0,  // 2: web.Auth.Login:input_type -> web.AuthLoginRequest
	1,  // 3: web.Auth.Captcha:input_type -> web.AuthCaptchaRequest
	4,  // 4: web.Auth.Register:input_type -> web.AuthRegisterRequest
	10, // 5: web.Auth.Forget:input_type -> web.AuthForgetRequest
	12, // 6: web.Auth.Oauth:input_type -> web.AuthOauthRequest
	17, // 7: web.Auth.OauthBind:input_type -> web.AuthOAuthBindRequest
	14, // 8: web.Auth.OauthLogin:input_type -> web.AuthOauthLoginRequest
	19, // 9: web.Auth.EmailLogin:input_type -> web.AuthEmailLoginRequest
	8,  // 10: web.Auth.RefreshToken:input_type -> web.AuthRefreshTokenRequest
	6,  // 11: web.Auth.Logout:input_type -> web.AuthLogoutRequest
	21, // 12: web.Auth.Cancel:input_type -> web.AuthCancelRequest
	3,  // 13: web.Auth.Login:output_type -> web.AuthLoginResponse
	2,  // 14: web.Auth.Captcha:output_type -> web.AuthCaptchaResponse
	5,  // 15: web.Auth.Register:output_type -> web.AuthRegisterResponse
	11, // 16: web.Auth.Forget:output_type -> web.AuthForgetResponse
	13, // 17: web.Auth.Oauth:output_type -> web.AuthOauthResponse
	18, // 18: web.Auth.OauthBind:output_type -> web.AuthOAuthBindResponse
	15, // 19: web.Auth.OauthLogin:output_type -> web.AuthOauthLoginResponse
	20, // 20: web.Auth.EmailLogin:output_type -> web.AuthEmailLoginResponse
	9,  // 21: web.Auth.RefreshToken:output_type -> web.AuthRefreshTokenResponse
	7,  // 22: web.Auth.Logout:output_type -> web.AuthLogoutResponse
	22, // 23: web.Auth.Cancel:output_type -> web.AuthCancelResponse
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_web_v1_auth_proto_init() }
func file_web_v1_auth_proto_init() {
	if File_web_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_v1_auth_proto_rawDesc), len(file_web_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_v1_auth_proto_goTypes,
		DependencyIndexes: file_web_v1_auth_proto_depIdxs,
		MessageInfos:      file_web_v1_auth_proto_msgTypes,
	}.Build()
	File_web_v1_auth_proto = out.File
	file_web_v1_auth_proto_goTypes = nil
	file_web_v1_auth_proto_depIdxs = nil
}
