// Code generated by protoc-gen-bff. DO NOT EDIT.
// Version: 1.0.0

package web

import (
	"context"

	"github.com/gin-gonic/gin"
)

// ICommonHandler BFF 接口
type ICommonHandler interface {

	// 发送短信验证码接口
	//    @Summary 发送短信验证码111222
	SendSms(ctx context.Context, in *CommonSendSmsRequest) (*CommonSendSmsResponse, error)
	// 发送邮件验证码接口
	SendEmail(ctx context.Context, in *CommonSendEmailRequest) (*CommonSendEmailResponse, error)
	//俺们就开始的那
	Test(ctx context.Context, in *CommonSendTestRequest) (*CommonSendTestResponse, error)
	// 探索位列表（仅返回 is_open=1）
	ExploreList(ctx context.Context, in *CommonExploreListRequest) (*CommonExploreListResponse, error)
	// 字典配置：按 key 批量获取（仅 status=启用），按 type 将 value 解析为 JSON 相应类型
	AppDictGet(ctx context.Context, in *CommonAppDictGetRequest) (*CommonAppDictGetResponse, error)
}

// RegisterCommonHandler 注册服务路由处理器
func RegisterCommonHandler(r gin.IRoutes, interceptor interface {
	ShouldProto(c *gin.Context, in any) error
	Do(fn func(ctx *gin.Context) (any, error)) func(c *gin.Context)
}, handler ICommonHandler) {
	if interceptor == nil {
		panic("interceptor is nil")
	}

	if handler == nil {
		panic("handler is nil")
	}

	r.POST("/api/v1/common/send-sms", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in CommonSendSmsRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.SendSms(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/common/send-email", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in CommonSendEmailRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.SendEmail(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/common/send-test", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in CommonSendTestRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Test(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/common/explore-list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in CommonExploreListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.ExploreList(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/common/app-dict", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in CommonAppDictGetRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.AppDictGet(ctx.Request.Context(), &in)
	}))

}
