// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: web/v1/common.proto

package web

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送短信验证码接口请求参数
type CommonSendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonSendSmsRequest) Reset() {
	*x = CommonSendSmsRequest{}
	mi := &file_web_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonSendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSendSmsRequest) ProtoMessage() {}

func (x *CommonSendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSendSmsRequest.ProtoReflect.Descriptor instead.
func (*CommonSendSmsRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *CommonSendSmsRequest) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *CommonSendSmsRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

// 发送短信验证码接口响应参数
type CommonSendSmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SmsCode       string                 `protobuf:"bytes,1,opt,name=sms_code,json=smsCode,proto3" json:"sms_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonSendSmsResponse) Reset() {
	*x = CommonSendSmsResponse{}
	mi := &file_web_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonSendSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSendSmsResponse) ProtoMessage() {}

func (x *CommonSendSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSendSmsResponse.ProtoReflect.Descriptor instead.
func (*CommonSendSmsResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *CommonSendSmsResponse) GetSmsCode() string {
	if x != nil {
		return x.SmsCode
	}
	return ""
}

// 发送邮件验证码接口请求参数
type CommonSendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"` // 可选的渠道标识：login, register, forget_account, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonSendEmailRequest) Reset() {
	*x = CommonSendEmailRequest{}
	mi := &file_web_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonSendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSendEmailRequest) ProtoMessage() {}

func (x *CommonSendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSendEmailRequest.ProtoReflect.Descriptor instead.
func (*CommonSendEmailRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *CommonSendEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CommonSendEmailRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

// 发送邮件验证码接口响应参数
type CommonSendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonSendEmailResponse) Reset() {
	*x = CommonSendEmailResponse{}
	mi := &file_web_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonSendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSendEmailResponse) ProtoMessage() {}

func (x *CommonSendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSendEmailResponse.ProtoReflect.Descriptor instead.
func (*CommonSendEmailResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{3}
}

// 发送邮件验证码接口请求参数
type CommonSendTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonSendTestRequest) Reset() {
	*x = CommonSendTestRequest{}
	mi := &file_web_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonSendTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSendTestRequest) ProtoMessage() {}

func (x *CommonSendTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSendTestRequest.ProtoReflect.Descriptor instead.
func (*CommonSendTestRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *CommonSendTestRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// 发送邮件验证码接口响应参数
type CommonSendTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonSendTestResponse) Reset() {
	*x = CommonSendTestResponse{}
	mi := &file_web_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonSendTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonSendTestResponse) ProtoMessage() {}

func (x *CommonSendTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonSendTestResponse.ProtoReflect.Descriptor instead.
func (*CommonSendTestResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{5}
}

// App 版本查询（GET /api/v1/common/app-version?platform=ios|android，路由在 router 单独注册）
type CommonAppVersionLatestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonAppVersionLatestRequest) Reset() {
	*x = CommonAppVersionLatestRequest{}
	mi := &file_web_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonAppVersionLatestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonAppVersionLatestRequest) ProtoMessage() {}

func (x *CommonAppVersionLatestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonAppVersionLatestRequest.ProtoReflect.Descriptor instead.
func (*CommonAppVersionLatestRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *CommonAppVersionLatestRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type CommonAppVersionLatestResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform          string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Channel           string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	LatestVersionName string                 `protobuf:"bytes,4,opt,name=latest_version_name,json=latestVersionName,proto3" json:"latest_version_name,omitempty"`
	UpgradeType       string                 `protobuf:"bytes,5,opt,name=upgrade_type,json=upgradeType,proto3" json:"upgrade_type,omitempty"`
	Title             string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	// 库中为 JSON 数组，接口返回已解析的 JSON 数组（protojson 下为 JSON array）
	ReleaseNotes  *structpb.ListValue `protobuf:"bytes,7,opt,name=release_notes,json=releaseNotes,proto3" json:"release_notes,omitempty"`
	DownloadUrls  *structpb.ListValue `protobuf:"bytes,8,opt,name=download_urls,json=downloadUrls,proto3" json:"download_urls,omitempty"`
	PublishedAt   string              `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonAppVersionLatestResponse) Reset() {
	*x = CommonAppVersionLatestResponse{}
	mi := &file_web_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonAppVersionLatestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonAppVersionLatestResponse) ProtoMessage() {}

func (x *CommonAppVersionLatestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonAppVersionLatestResponse.ProtoReflect.Descriptor instead.
func (*CommonAppVersionLatestResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *CommonAppVersionLatestResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommonAppVersionLatestResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CommonAppVersionLatestResponse) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CommonAppVersionLatestResponse) GetLatestVersionName() string {
	if x != nil {
		return x.LatestVersionName
	}
	return ""
}

func (x *CommonAppVersionLatestResponse) GetUpgradeType() string {
	if x != nil {
		return x.UpgradeType
	}
	return ""
}

func (x *CommonAppVersionLatestResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CommonAppVersionLatestResponse) GetReleaseNotes() *structpb.ListValue {
	if x != nil {
		return x.ReleaseNotes
	}
	return nil
}

func (x *CommonAppVersionLatestResponse) GetDownloadUrls() *structpb.ListValue {
	if x != nil {
		return x.DownloadUrls
	}
	return nil
}

func (x *CommonAppVersionLatestResponse) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

type CommonExploreListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonExploreListRequest) Reset() {
	*x = CommonExploreListRequest{}
	mi := &file_web_v1_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonExploreListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonExploreListRequest) ProtoMessage() {}

func (x *CommonExploreListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonExploreListRequest.ProtoReflect.Descriptor instead.
func (*CommonExploreListRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{8}
}

type CommonExploreListResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Items         []*CommonExploreListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonExploreListResponse) Reset() {
	*x = CommonExploreListResponse{}
	mi := &file_web_v1_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonExploreListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonExploreListResponse) ProtoMessage() {}

func (x *CommonExploreListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonExploreListResponse.ProtoReflect.Descriptor instead.
func (*CommonExploreListResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{9}
}

func (x *CommonExploreListResponse) GetItems() []*CommonExploreListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CommonAppDictGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求的 key 列表，1～100 个；仅返回库中已启用项，未命中或关闭的 key 不出现在结果中
	Keys          []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonAppDictGetRequest) Reset() {
	*x = CommonAppDictGetRequest{}
	mi := &file_web_v1_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonAppDictGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonAppDictGetRequest) ProtoMessage() {}

func (x *CommonAppDictGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonAppDictGetRequest.ProtoReflect.Descriptor instead.
func (*CommonAppDictGetRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{10}
}

func (x *CommonAppDictGetRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type CommonAppDictItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Title string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type  string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// 已解析：text→字符串，num→数字，list→JSON 数组，object→JSON 对象
	ParsedValue   *structpb.Value `protobuf:"bytes,4,opt,name=parsed_value,json=parsedValue,proto3" json:"parsed_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonAppDictItem) Reset() {
	*x = CommonAppDictItem{}
	mi := &file_web_v1_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonAppDictItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonAppDictItem) ProtoMessage() {}

func (x *CommonAppDictItem) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonAppDictItem.ProtoReflect.Descriptor instead.
func (*CommonAppDictItem) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{11}
}

func (x *CommonAppDictItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CommonAppDictItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CommonAppDictItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CommonAppDictItem) GetParsedValue() *structpb.Value {
	if x != nil {
		return x.ParsedValue
	}
	return nil
}

type CommonAppDictGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CommonAppDictItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonAppDictGetResponse) Reset() {
	*x = CommonAppDictGetResponse{}
	mi := &file_web_v1_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonAppDictGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonAppDictGetResponse) ProtoMessage() {}

func (x *CommonAppDictGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonAppDictGetResponse.ProtoReflect.Descriptor instead.
func (*CommonAppDictGetResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{12}
}

func (x *CommonAppDictGetResponse) GetItems() []*CommonAppDictItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CommonAppModulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonAppModulesRequest) Reset() {
	*x = CommonAppModulesRequest{}
	mi := &file_web_v1_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonAppModulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonAppModulesRequest) ProtoMessage() {}

func (x *CommonAppModulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonAppModulesRequest.ProtoReflect.Descriptor instead.
func (*CommonAppModulesRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{13}
}

type CommonAppModulesResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Items         []*CommonAppModulesResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonAppModulesResponse) Reset() {
	*x = CommonAppModulesResponse{}
	mi := &file_web_v1_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonAppModulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonAppModulesResponse) ProtoMessage() {}

func (x *CommonAppModulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonAppModulesResponse.ProtoReflect.Descriptor instead.
func (*CommonAppModulesResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{14}
}

func (x *CommonAppModulesResponse) GetItems() []*CommonAppModulesResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CommonExploreListResponse_Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Image string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Url   string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// index-首页，tab-选项
	Position string `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	// 排序权重，越大越靠前（与库 sort 一致）
	Sort          int32 `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonExploreListResponse_Item) Reset() {
	*x = CommonExploreListResponse_Item{}
	mi := &file_web_v1_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonExploreListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonExploreListResponse_Item) ProtoMessage() {}

func (x *CommonExploreListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonExploreListResponse_Item.ProtoReflect.Descriptor instead.
func (*CommonExploreListResponse_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{9, 0}
}

func (x *CommonExploreListResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommonExploreListResponse_Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CommonExploreListResponse_Item) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CommonExploreListResponse_Item) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CommonExploreListResponse_Item) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *CommonExploreListResponse_Item) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type CommonAppModulesResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	IsOpen        int32                  `protobuf:"varint,4,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonAppModulesResponse_Item) Reset() {
	*x = CommonAppModulesResponse_Item{}
	mi := &file_web_v1_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonAppModulesResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonAppModulesResponse_Item) ProtoMessage() {}

func (x *CommonAppModulesResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonAppModulesResponse_Item.ProtoReflect.Descriptor instead.
func (*CommonAppModulesResponse_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_common_proto_rawDescGZIP(), []int{14, 0}
}

func (x *CommonAppModulesResponse_Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CommonAppModulesResponse_Item) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CommonAppModulesResponse_Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CommonAppModulesResponse_Item) GetIsOpen() int32 {
	if x != nil {
		return x.IsOpen
	}
	return 0
}

var File_web_v1_common_proto protoreflect.FileDescriptor

const file_web_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x13web/v1/common.proto\x12\x03web\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x96\x01\n" +
	"\x14CommonSendSmsRequest\x12 \n" +
	"\x06mobile\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x98\x01\vR\x06mobile\x12\\\n" +
	"\achannel\x18\x02 \x01(\tBB\xbaH?r=R\x05loginR\bregisterR\x0eforget_accountR\x0echange_accountR\n" +
	"oauth_bindR\achannel\"2\n" +
	"\x15CommonSendSmsResponse\x12\x19\n" +
	"\bsms_code\x18\x01 \x01(\tR\asmsCode\"Q\n" +
	"\x16CommonSendEmailRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x06R\x05email\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\"\x19\n" +
	"\x17CommonSendEmailResponse\"6\n" +
	"\x15CommonSendTestRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x06R\x05email\"\x18\n" +
	"\x16CommonSendTestResponse\"P\n" +
	"\x1dCommonAppVersionLatestRequest\x12/\n" +
	"\bplatform\x18\x01 \x01(\tB\x13\xbaH\x10r\x0eR\x03iosR\aandroidR\bplatform\"\xf4\x02\n" +
	"\x1eCommonAppVersionLatestResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12.\n" +
	"\x13latest_version_name\x18\x04 \x01(\tR\x11latestVersionName\x12!\n" +
	"\fupgrade_type\x18\x05 \x01(\tR\vupgradeType\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12?\n" +
	"\rrelease_notes\x18\a \x01(\v2\x1a.google.protobuf.ListValueR\freleaseNotes\x12?\n" +
	"\rdownload_urls\x18\b \x01(\v2\x1a.google.protobuf.ListValueR\fdownloadUrls\x12!\n" +
	"\fpublished_at\x18\t \x01(\tR\vpublishedAt\"\x1a\n" +
	"\x18CommonExploreListRequest\"\xdd\x01\n" +
	"\x19CommonExploreListResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.web.CommonExploreListResponse.ItemR\x05items\x1a\x84\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\tR\bposition\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\"9\n" +
	"\x17CommonAppDictGetRequest\x12\x1e\n" +
	"\x04keys\x18\x01 \x03(\tB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x10dR\x04keys\"\x8a\x01\n" +
	"\x11CommonAppDictItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x129\n" +
	"\fparsed_value\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\vparsedValue\"H\n" +
	"\x18CommonAppDictGetResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.web.CommonAppDictItemR\x05items\"\x19\n" +
	"\x17CommonAppModulesRequest\"\xaf\x01\n" +
	"\x18CommonAppModulesResponse\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".web.CommonAppModulesResponse.ItemR\x05items\x1aY\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x17\n" +
	"\ais_open\x18\x04 \x01(\x05R\x06isOpen2\x99\x05\n" +
	"\x06Common\x12d\n" +
	"\aSendSms\x12\x19.web.CommonSendSmsRequest\x1a\x1a.web.CommonSendSmsResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/common/send-sms\x12l\n" +
	"\tSendEmail\x12\x1b.web.CommonSendEmailRequest\x1a\x1c.web.CommonSendEmailResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/common/send-email\x12d\n" +
	"\x04Test\x12\x1a.web.CommonSendTestRequest\x1a\x1b.web.CommonSendTestResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/common/send-test\x12t\n" +
	"\vExploreList\x12\x1d.web.CommonExploreListRequest\x1a\x1e.web.CommonExploreListResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/common/explore-list\x12m\n" +
	"\n" +
	"AppDictGet\x12\x1c.web.CommonAppDictGetRequest\x1a\x1d.web.CommonAppDictGetResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/common/app-dict\x12p\n" +
	"\n" +
	"AppModules\x12\x1c.web.CommonAppModulesRequest\x1a\x1d.web.CommonAppModulesResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/common/app-modulesB\fZ\n" +
	"web/v1;webb\x06proto3"

var (
	file_web_v1_common_proto_rawDescOnce sync.Once
	file_web_v1_common_proto_rawDescData []byte
)

func file_web_v1_common_proto_rawDescGZIP() []byte {
	file_web_v1_common_proto_rawDescOnce.Do(func() {
		file_web_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_v1_common_proto_rawDesc), len(file_web_v1_common_proto_rawDesc)))
	})
	return file_web_v1_common_proto_rawDescData
}

var file_web_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_web_v1_common_proto_goTypes = []any{
	(*CommonSendSmsRequest)(nil),           // 0: web.CommonSendSmsRequest
	(*CommonSendSmsResponse)(nil),          // 1: web.CommonSendSmsResponse
	(*CommonSendEmailRequest)(nil),         // 2: web.CommonSendEmailRequest
	(*CommonSendEmailResponse)(nil),        // 3: web.CommonSendEmailResponse
	(*CommonSendTestRequest)(nil),          // 4: web.CommonSendTestRequest
	(*CommonSendTestResponse)(nil),         // 5: web.CommonSendTestResponse
	(*CommonAppVersionLatestRequest)(nil),  // 6: web.CommonAppVersionLatestRequest
	(*CommonAppVersionLatestResponse)(nil), // 7: web.CommonAppVersionLatestResponse
	(*CommonExploreListRequest)(nil),       // 8: web.CommonExploreListRequest
	(*CommonExploreListResponse)(nil),      // 9: web.CommonExploreListResponse
	(*CommonAppDictGetRequest)(nil),        // 10: web.CommonAppDictGetRequest
	(*CommonAppDictItem)(nil),              // 11: web.CommonAppDictItem
	(*CommonAppDictGetResponse)(nil),       // 12: web.CommonAppDictGetResponse
	(*CommonAppModulesRequest)(nil),        // 13: web.CommonAppModulesRequest
	(*CommonAppModulesResponse)(nil),       // 14: web.CommonAppModulesResponse
	(*CommonExploreListResponse_Item)(nil), // 15: web.CommonExploreListResponse.Item
	(*CommonAppModulesResponse_Item)(nil),  // 16: web.CommonAppModulesResponse.Item
	(*structpb.ListValue)(nil),             // 17: google.protobuf.ListValue
	(*structpb.Value)(nil),                 // 18: google.protobuf.Value
}
var file_web_v1_common_proto_depIdxs = []int32{
	17, // 0: web.CommonAppVersionLatestResponse.release_notes:type_name -> google.protobuf.ListValue
	17, // 1: web.CommonAppVersionLatestResponse.download_urls:type_name -> google.protobuf.ListValue
	15, // 2: web.CommonExploreListResponse.items:type_name -> web.CommonExploreListResponse.Item
	18, // 3: web.CommonAppDictItem.parsed_value:type_name -> google.protobuf.Value
	11, // 4: web.CommonAppDictGetResponse.items:type_name -> web.CommonAppDictItem
	16, // 5: web.CommonAppModulesResponse.items:type_name -> web.CommonAppModulesResponse.Item
	0,  // 6: web.Common.SendSms:input_type -> web.CommonSendSmsRequest
	2,  // 7: web.Common.SendEmail:input_type -> web.CommonSendEmailRequest
	4,  // 8: web.Common.Test:input_type -> web.CommonSendTestRequest
	8,  // 9: web.Common.ExploreList:input_type -> web.CommonExploreListRequest
	10, // 10: web.Common.AppDictGet:input_type -> web.CommonAppDictGetRequest
	13, // 11: web.Common.AppModules:input_type -> web.CommonAppModulesRequest
	1,  // 12: web.Common.SendSms:output_type -> web.CommonSendSmsResponse
	3,  // 13: web.Common.SendEmail:output_type -> web.CommonSendEmailResponse
	5,  // 14: web.Common.Test:output_type -> web.CommonSendTestResponse
	9,  // 15: web.Common.ExploreList:output_type -> web.CommonExploreListResponse
	12, // 16: web.Common.AppDictGet:output_type -> web.CommonAppDictGetResponse
	14, // 17: web.Common.AppModules:output_type -> web.CommonAppModulesResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_web_v1_common_proto_init() }
func file_web_v1_common_proto_init() {
	if File_web_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_v1_common_proto_rawDesc), len(file_web_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_v1_common_proto_goTypes,
		DependencyIndexes: file_web_v1_common_proto_depIdxs,
		MessageInfos:      file_web_v1_common_proto_msgTypes,
	}.Build()
	File_web_v1_common_proto = out.File
	file_web_v1_common_proto_goTypes = nil
	file_web_v1_common_proto_depIdxs = nil
}
