// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: web/v1/group.proto

package web

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 群列表接口请求参数
type GroupListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupListRequest) Reset() {
	*x = GroupListRequest{}
	mi := &file_web_v1_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListRequest) ProtoMessage() {}

func (x *GroupListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListRequest.ProtoReflect.Descriptor instead.
func (*GroupListRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{0}
}

// 群列表接口响应参数
type GroupListResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*GroupListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupListResponse) Reset() {
	*x = GroupListResponse{}
	mi := &file_web_v1_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListResponse) ProtoMessage() {}

func (x *GroupListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListResponse.ProtoReflect.Descriptor instead.
func (*GroupListResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{1}
}

func (x *GroupListResponse) GetItems() []*GroupListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 创建群聊接口请求参数
type GroupCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserIds       []int32                `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupCreateRequest) Reset() {
	*x = GroupCreateRequest{}
	mi := &file_web_v1_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreateRequest) ProtoMessage() {}

func (x *GroupCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupCreateRequest.ProtoReflect.Descriptor instead.
func (*GroupCreateRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{2}
}

func (x *GroupCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupCreateRequest) GetUserIds() []int32 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// 创建群聊接口响应参数
type GroupCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupCreateResponse) Reset() {
	*x = GroupCreateResponse{}
	mi := &file_web_v1_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreateResponse) ProtoMessage() {}

func (x *GroupCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupCreateResponse.ProtoReflect.Descriptor instead.
func (*GroupCreateResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{3}
}

func (x *GroupCreateResponse) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 群聊详情接口请求参数
type GroupDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupDetailRequest) Reset() {
	*x = GroupDetailRequest{}
	mi := &file_web_v1_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupDetailRequest) ProtoMessage() {}

func (x *GroupDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupDetailRequest.ProtoReflect.Descriptor instead.
func (*GroupDetailRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{4}
}

func (x *GroupDetailRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 群聊详情接口响应参数
type GroupDetailResponse struct {
	state     protoimpl.MessageState      `protogen:"open.v1"`
	GroupId   int32                       `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName string                      `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Profile   string                      `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	Avatar    string                      `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	CreatedAt string                      `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsManager bool                        `protobuf:"varint,6,opt,name=is_manager,json=isManager,proto3" json:"is_manager,omitempty"`
	IsDisturb int32                       `protobuf:"varint,7,opt,name=is_disturb,json=isDisturb,proto3" json:"is_disturb,omitempty"`
	VisitCard string                      `protobuf:"bytes,8,opt,name=visit_card,json=visitCard,proto3" json:"visit_card,omitempty"`
	IsMute    int32                       `protobuf:"varint,9,opt,name=is_mute,json=isMute,proto3" json:"is_mute,omitempty"`
	IsOvert   int32                       `protobuf:"varint,10,opt,name=is_overt,json=isOvert,proto3" json:"is_overt,omitempty"`
	Notice    *GroupDetailResponse_Notice `protobuf:"bytes,11,opt,name=notice,proto3" json:"notice,omitempty"`
	// 是否允许群内互加好友：1 允许 2 不允许
	IsAllowInvite int32 `protobuf:"varint,12,opt,name=is_allow_invite,json=isAllowInvite,proto3" json:"is_allow_invite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupDetailResponse) Reset() {
	*x = GroupDetailResponse{}
	mi := &file_web_v1_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupDetailResponse) ProtoMessage() {}

func (x *GroupDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupDetailResponse.ProtoReflect.Descriptor instead.
func (*GroupDetailResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{5}
}

func (x *GroupDetailResponse) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupDetailResponse) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupDetailResponse) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *GroupDetailResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupDetailResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GroupDetailResponse) GetIsManager() bool {
	if x != nil {
		return x.IsManager
	}
	return false
}

func (x *GroupDetailResponse) GetIsDisturb() int32 {
	if x != nil {
		return x.IsDisturb
	}
	return 0
}

func (x *GroupDetailResponse) GetVisitCard() string {
	if x != nil {
		return x.VisitCard
	}
	return ""
}

func (x *GroupDetailResponse) GetIsMute() int32 {
	if x != nil {
		return x.IsMute
	}
	return 0
}

func (x *GroupDetailResponse) GetIsOvert() int32 {
	if x != nil {
		return x.IsOvert
	}
	return 0
}

func (x *GroupDetailResponse) GetNotice() *GroupDetailResponse_Notice {
	if x != nil {
		return x.Notice
	}
	return nil
}

func (x *GroupDetailResponse) GetIsAllowInvite() int32 {
	if x != nil {
		return x.IsAllowInvite
	}
	return 0
}

// 群成员列表接口请求参数
type GroupMemberListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberListRequest) Reset() {
	*x = GroupMemberListRequest{}
	mi := &file_web_v1_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberListRequest) ProtoMessage() {}

func (x *GroupMemberListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberListRequest.ProtoReflect.Descriptor instead.
func (*GroupMemberListRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{6}
}

func (x *GroupMemberListRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 群成员列表接口响应参数
type GroupMemberListResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Items         []*GroupMemberListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberListResponse) Reset() {
	*x = GroupMemberListResponse{}
	mi := &file_web_v1_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberListResponse) ProtoMessage() {}

func (x *GroupMemberListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberListResponse.ProtoReflect.Descriptor instead.
func (*GroupMemberListResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{7}
}

func (x *GroupMemberListResponse) GetItems() []*GroupMemberListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 解散群聊接口请求参数
type GroupDismissRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupDismissRequest) Reset() {
	*x = GroupDismissRequest{}
	mi := &file_web_v1_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupDismissRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupDismissRequest) ProtoMessage() {}

func (x *GroupDismissRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupDismissRequest.ProtoReflect.Descriptor instead.
func (*GroupDismissRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{8}
}

func (x *GroupDismissRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 解散群聊接口响应参数
type GroupDismissResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupDismissResponse) Reset() {
	*x = GroupDismissResponse{}
	mi := &file_web_v1_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupDismissResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupDismissResponse) ProtoMessage() {}

func (x *GroupDismissResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupDismissResponse.ProtoReflect.Descriptor instead.
func (*GroupDismissResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{9}
}

// 加入群聊接口请求参数
type GroupInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserIds       []int32                `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInviteRequest) Reset() {
	*x = GroupInviteRequest{}
	mi := &file_web_v1_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInviteRequest) ProtoMessage() {}

func (x *GroupInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInviteRequest.ProtoReflect.Descriptor instead.
func (*GroupInviteRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{10}
}

func (x *GroupInviteRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupInviteRequest) GetUserIds() []int32 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// 加入群聊接口响应参数
type GroupInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInviteResponse) Reset() {
	*x = GroupInviteResponse{}
	mi := &file_web_v1_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInviteResponse) ProtoMessage() {}

func (x *GroupInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInviteResponse.ProtoReflect.Descriptor instead.
func (*GroupInviteResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{11}
}

// 获取可邀请好友列表请求参数
type GetInviteFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteFriendsRequest) Reset() {
	*x = GetInviteFriendsRequest{}
	mi := &file_web_v1_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteFriendsRequest) ProtoMessage() {}

func (x *GetInviteFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteFriendsRequest.ProtoReflect.Descriptor instead.
func (*GetInviteFriendsRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{12}
}

func (x *GetInviteFriendsRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 获取可邀请好友列表响应参数
type GetInviteFriendsResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Items         []*GetInviteFriendsResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteFriendsResponse) Reset() {
	*x = GetInviteFriendsResponse{}
	mi := &file_web_v1_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteFriendsResponse) ProtoMessage() {}

func (x *GetInviteFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteFriendsResponse.ProtoReflect.Descriptor instead.
func (*GetInviteFriendsResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{13}
}

func (x *GetInviteFriendsResponse) GetItems() []*GetInviteFriendsResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 退出群聊接口请求参数
type GroupSecedeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSecedeRequest) Reset() {
	*x = GroupSecedeRequest{}
	mi := &file_web_v1_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSecedeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSecedeRequest) ProtoMessage() {}

func (x *GroupSecedeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSecedeRequest.ProtoReflect.Descriptor instead.
func (*GroupSecedeRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{14}
}

func (x *GroupSecedeRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 退出群聊接口响应参数
type GroupSecedeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSecedeResponse) Reset() {
	*x = GroupSecedeResponse{}
	mi := &file_web_v1_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSecedeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSecedeResponse) ProtoMessage() {}

func (x *GroupSecedeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSecedeResponse.ProtoReflect.Descriptor instead.
func (*GroupSecedeResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{15}
}

// 设置群聊接口请求参数
type GroupSettingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Profile       string                 `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSettingRequest) Reset() {
	*x = GroupSettingRequest{}
	mi := &file_web_v1_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSettingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSettingRequest) ProtoMessage() {}

func (x *GroupSettingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSettingRequest.ProtoReflect.Descriptor instead.
func (*GroupSettingRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{16}
}

func (x *GroupSettingRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupSettingRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupSettingRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupSettingRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

// 设置群聊接口响应参数
type GroupSettingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSettingResponse) Reset() {
	*x = GroupSettingResponse{}
	mi := &file_web_v1_group_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSettingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSettingResponse) ProtoMessage() {}

func (x *GroupSettingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSettingResponse.ProtoReflect.Descriptor instead.
func (*GroupSettingResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{17}
}

// 群聊名片更新接口请求参数
type GroupRemarkUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Remark        string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRemarkUpdateRequest) Reset() {
	*x = GroupRemarkUpdateRequest{}
	mi := &file_web_v1_group_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRemarkUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRemarkUpdateRequest) ProtoMessage() {}

func (x *GroupRemarkUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRemarkUpdateRequest.ProtoReflect.Descriptor instead.
func (*GroupRemarkUpdateRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{18}
}

func (x *GroupRemarkUpdateRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupRemarkUpdateRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 群聊名片更新接口响应参数
type GroupRemarkUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRemarkUpdateResponse) Reset() {
	*x = GroupRemarkUpdateResponse{}
	mi := &file_web_v1_group_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRemarkUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRemarkUpdateResponse) ProtoMessage() {}

func (x *GroupRemarkUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRemarkUpdateResponse.ProtoReflect.Descriptor instead.
func (*GroupRemarkUpdateResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{19}
}

// 移出群成员接口请求参数
type GroupRemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserIds       []int32                `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRemoveMemberRequest) Reset() {
	*x = GroupRemoveMemberRequest{}
	mi := &file_web_v1_group_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRemoveMemberRequest) ProtoMessage() {}

func (x *GroupRemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*GroupRemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{20}
}

func (x *GroupRemoveMemberRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupRemoveMemberRequest) GetUserIds() []int32 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// 移出群成员接口响应参数
type GroupRemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRemoveMemberResponse) Reset() {
	*x = GroupRemoveMemberResponse{}
	mi := &file_web_v1_group_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRemoveMemberResponse) ProtoMessage() {}

func (x *GroupRemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*GroupRemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{21}
}

// 公开群聊列表请求参数
type GroupOvertListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupOvertListRequest) Reset() {
	*x = GroupOvertListRequest{}
	mi := &file_web_v1_group_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupOvertListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupOvertListRequest) ProtoMessage() {}

func (x *GroupOvertListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupOvertListRequest.ProtoReflect.Descriptor instead.
func (*GroupOvertListRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{22}
}

func (x *GroupOvertListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GroupOvertListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 公开群聊列表响应参数
type GroupOvertListResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Items         []*GroupOvertListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Next          bool                           `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupOvertListResponse) Reset() {
	*x = GroupOvertListResponse{}
	mi := &file_web_v1_group_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupOvertListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupOvertListResponse) ProtoMessage() {}

func (x *GroupOvertListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupOvertListResponse.ProtoReflect.Descriptor instead.
func (*GroupOvertListResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{23}
}

func (x *GroupOvertListResponse) GetItems() []*GroupOvertListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GroupOvertListResponse) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

// 群主更换接口请求参数
type GroupHandoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupHandoverRequest) Reset() {
	*x = GroupHandoverRequest{}
	mi := &file_web_v1_group_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupHandoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupHandoverRequest) ProtoMessage() {}

func (x *GroupHandoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupHandoverRequest.ProtoReflect.Descriptor instead.
func (*GroupHandoverRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{24}
}

func (x *GroupHandoverRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupHandoverRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 群主更换接口响应参数
type GroupHandoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupHandoverResponse) Reset() {
	*x = GroupHandoverResponse{}
	mi := &file_web_v1_group_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupHandoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupHandoverResponse) ProtoMessage() {}

func (x *GroupHandoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupHandoverResponse.ProtoReflect.Descriptor instead.
func (*GroupHandoverResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{25}
}

// 分配管理员接口请求参数
type GroupAssignAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        int32                  `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAssignAdminRequest) Reset() {
	*x = GroupAssignAdminRequest{}
	mi := &file_web_v1_group_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAssignAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAssignAdminRequest) ProtoMessage() {}

func (x *GroupAssignAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAssignAdminRequest.ProtoReflect.Descriptor instead.
func (*GroupAssignAdminRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{26}
}

func (x *GroupAssignAdminRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupAssignAdminRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupAssignAdminRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// 分配管理员接口响应参数
type GroupAssignAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAssignAdminResponse) Reset() {
	*x = GroupAssignAdminResponse{}
	mi := &file_web_v1_group_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAssignAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAssignAdminResponse) ProtoMessage() {}

func (x *GroupAssignAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAssignAdminResponse.ProtoReflect.Descriptor instead.
func (*GroupAssignAdminResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{27}
}

// 群成员禁言接口请求参数
type GroupNoSpeakRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        int32                  `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupNoSpeakRequest) Reset() {
	*x = GroupNoSpeakRequest{}
	mi := &file_web_v1_group_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupNoSpeakRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupNoSpeakRequest) ProtoMessage() {}

func (x *GroupNoSpeakRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupNoSpeakRequest.ProtoReflect.Descriptor instead.
func (*GroupNoSpeakRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{28}
}

func (x *GroupNoSpeakRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupNoSpeakRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupNoSpeakRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// 群成员禁言接口响应参数
type GroupNoSpeakResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupNoSpeakResponse) Reset() {
	*x = GroupNoSpeakResponse{}
	mi := &file_web_v1_group_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupNoSpeakResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupNoSpeakResponse) ProtoMessage() {}

func (x *GroupNoSpeakResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupNoSpeakResponse.ProtoReflect.Descriptor instead.
func (*GroupNoSpeakResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{29}
}

// 群禁言接口请求参数
type GroupMuteRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupId int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// 操作方式  1:开启全员禁言  2:解除全员禁言
	Action        int32 `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMuteRequest) Reset() {
	*x = GroupMuteRequest{}
	mi := &file_web_v1_group_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMuteRequest) ProtoMessage() {}

func (x *GroupMuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMuteRequest.ProtoReflect.Descriptor instead.
func (*GroupMuteRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{30}
}

func (x *GroupMuteRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMuteRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// 群禁言接口响应参数
type GroupMuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMuteResponse) Reset() {
	*x = GroupMuteResponse{}
	mi := &file_web_v1_group_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMuteResponse) ProtoMessage() {}

func (x *GroupMuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMuteResponse.ProtoReflect.Descriptor instead.
func (*GroupMuteResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{31}
}

// 群内互加好友开关请求
type GroupAllowInviteRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupId int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// 1:不允许 2:允许
	Action        int32 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAllowInviteRequest) Reset() {
	*x = GroupAllowInviteRequest{}
	mi := &file_web_v1_group_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAllowInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAllowInviteRequest) ProtoMessage() {}

func (x *GroupAllowInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAllowInviteRequest.ProtoReflect.Descriptor instead.
func (*GroupAllowInviteRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{32}
}

func (x *GroupAllowInviteRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupAllowInviteRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// 群内互加好友开关响应
type GroupAllowInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAllowInviteResponse) Reset() {
	*x = GroupAllowInviteResponse{}
	mi := &file_web_v1_group_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAllowInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAllowInviteResponse) ProtoMessage() {}

func (x *GroupAllowInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAllowInviteResponse.ProtoReflect.Descriptor instead.
func (*GroupAllowInviteResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{33}
}

// 群公开修改接口请求参数
type GroupOvertRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupId int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// 操作方式 1:关闭  2:开启
	Action        int32 `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupOvertRequest) Reset() {
	*x = GroupOvertRequest{}
	mi := &file_web_v1_group_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupOvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupOvertRequest) ProtoMessage() {}

func (x *GroupOvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupOvertRequest.ProtoReflect.Descriptor instead.
func (*GroupOvertRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{34}
}

func (x *GroupOvertRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupOvertRequest) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

// 群公开修改接口响应参数
type GroupOvertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupOvertResponse) Reset() {
	*x = GroupOvertResponse{}
	mi := &file_web_v1_group_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupOvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupOvertResponse) ProtoMessage() {}

func (x *GroupOvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupOvertResponse.ProtoReflect.Descriptor instead.
func (*GroupOvertResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{35}
}

// 群马甲用户列表请求
type GroupFakersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupFakersRequest) Reset() {
	*x = GroupFakersRequest{}
	mi := &file_web_v1_group_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupFakersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupFakersRequest) ProtoMessage() {}

func (x *GroupFakersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupFakersRequest.ProtoReflect.Descriptor instead.
func (*GroupFakersRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{36}
}

func (x *GroupFakersRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 群马甲用户列表响应
type GroupFakersResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*GroupFakersResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupFakersResponse) Reset() {
	*x = GroupFakersResponse{}
	mi := &file_web_v1_group_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupFakersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupFakersResponse) ProtoMessage() {}

func (x *GroupFakersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupFakersResponse.ProtoReflect.Descriptor instead.
func (*GroupFakersResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{37}
}

func (x *GroupFakersResponse) GetItems() []*GroupFakersResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GroupListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Profile       string                 `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	Leader        int32                  `protobuf:"varint,5,opt,name=leader,proto3" json:"leader,omitempty"`
	CreatorId     int32                  `protobuf:"varint,7,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupListResponse_Item) Reset() {
	*x = GroupListResponse_Item{}
	mi := &file_web_v1_group_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupListResponse_Item) ProtoMessage() {}

func (x *GroupListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupListResponse_Item.ProtoReflect.Descriptor instead.
func (*GroupListResponse_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GroupListResponse_Item) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupListResponse_Item) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupListResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupListResponse_Item) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *GroupListResponse_Item) GetLeader() int32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *GroupListResponse_Item) GetCreatorId() int32 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

type GroupDetailResponse_Notice struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Content        string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ModifyUserName string                 `protobuf:"bytes,5,opt,name=modify_user_name,json=modifyUserName,proto3" json:"modify_user_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GroupDetailResponse_Notice) Reset() {
	*x = GroupDetailResponse_Notice{}
	mi := &file_web_v1_group_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupDetailResponse_Notice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupDetailResponse_Notice) ProtoMessage() {}

func (x *GroupDetailResponse_Notice) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupDetailResponse_Notice.ProtoReflect.Descriptor instead.
func (*GroupDetailResponse_Notice) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GroupDetailResponse_Notice) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GroupDetailResponse_Notice) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GroupDetailResponse_Notice) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GroupDetailResponse_Notice) GetModifyUserName() string {
	if x != nil {
		return x.ModifyUserName
	}
	return ""
}

type GroupMemberListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender        int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Leader        int32                  `protobuf:"varint,5,opt,name=leader,proto3" json:"leader,omitempty"`
	IsMute        int32                  `protobuf:"varint,6,opt,name=is_mute,json=isMute,proto3" json:"is_mute,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	Motto         string                 `protobuf:"bytes,8,opt,name=motto,proto3" json:"motto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberListResponse_Item) Reset() {
	*x = GroupMemberListResponse_Item{}
	mi := &file_web_v1_group_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberListResponse_Item) ProtoMessage() {}

func (x *GroupMemberListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberListResponse_Item.ProtoReflect.Descriptor instead.
func (*GroupMemberListResponse_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GroupMemberListResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMemberListResponse_Item) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupMemberListResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupMemberListResponse_Item) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *GroupMemberListResponse_Item) GetLeader() int32 {
	if x != nil {
		return x.Leader
	}
	return 0
}

func (x *GroupMemberListResponse_Item) GetIsMute() int32 {
	if x != nil {
		return x.IsMute
	}
	return 0
}

func (x *GroupMemberListResponse_Item) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *GroupMemberListResponse_Item) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

type GetInviteFriendsResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender        int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteFriendsResponse_Item) Reset() {
	*x = GetInviteFriendsResponse_Item{}
	mi := &file_web_v1_group_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteFriendsResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteFriendsResponse_Item) ProtoMessage() {}

func (x *GetInviteFriendsResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteFriendsResponse_Item.ProtoReflect.Descriptor instead.
func (*GetInviteFriendsResponse_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{13, 0}
}

func (x *GetInviteFriendsResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetInviteFriendsResponse_Item) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetInviteFriendsResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetInviteFriendsResponse_Item) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *GetInviteFriendsResponse_Item) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type GroupOvertListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Profile       string                 `protobuf:"bytes,5,opt,name=profile,proto3" json:"profile,omitempty"`
	Count         int32                  `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	MaxNum        int32                  `protobuf:"varint,7,opt,name=max_num,json=maxNum,proto3" json:"max_num,omitempty"`
	IsMember      bool                   `protobuf:"varint,8,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupOvertListResponse_Item) Reset() {
	*x = GroupOvertListResponse_Item{}
	mi := &file_web_v1_group_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupOvertListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupOvertListResponse_Item) ProtoMessage() {}

func (x *GroupOvertListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupOvertListResponse_Item.ProtoReflect.Descriptor instead.
func (*GroupOvertListResponse_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{23, 0}
}

func (x *GroupOvertListResponse_Item) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupOvertListResponse_Item) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GroupOvertListResponse_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupOvertListResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GroupOvertListResponse_Item) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *GroupOvertListResponse_Item) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GroupOvertListResponse_Item) GetMaxNum() int32 {
	if x != nil {
		return x.MaxNum
	}
	return 0
}

func (x *GroupOvertListResponse_Item) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

func (x *GroupOvertListResponse_Item) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GroupFakersResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupFakersResponse_Item) Reset() {
	*x = GroupFakersResponse_Item{}
	mi := &file_web_v1_group_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupFakersResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupFakersResponse_Item) ProtoMessage() {}

func (x *GroupFakersResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_group_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupFakersResponse_Item.ProtoReflect.Descriptor instead.
func (*GroupFakersResponse_Item) Descriptor() ([]byte, []int) {
	return file_web_v1_group_proto_rawDescGZIP(), []int{37, 0}
}

func (x *GroupFakersResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupFakersResponse_Item) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GroupFakersResponse_Item) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupFakersResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_web_v1_group_proto protoreflect.FileDescriptor

const file_web_v1_group_proto_rawDesc = "" +
	"\n" +
	"\x12web/v1/group.proto\x12\x03web\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x12\n" +
	"\x10GroupListRequest\"\x9c\x02\n" +
	"\x11GroupListResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.web.GroupListResponse.ItemB\x04\xe2A\x01\x02R\x05items\x1a\xcd\x01\n" +
	"\x04Item\x12\x1f\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\agroupId\x12#\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\tgroupName\x12\x1c\n" +
	"\x06avatar\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\x06avatar\x12\x1e\n" +
	"\aprofile\x18\x04 \x01(\tB\x04\xe2A\x01\x02R\aprofile\x12\x1c\n" +
	"\x06leader\x18\x05 \x01(\x05B\x04\xe2A\x01\x02R\x06leader\x12#\n" +
	"\n" +
	"creator_id\x18\a \x01(\x05B\x04\xe2A\x01\x02R\tcreatorId\"V\n" +
	"\x12GroupCreateRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12#\n" +
	"\buser_ids\x18\x02 \x03(\x05B\b\xbaH\x05\x92\x01\x02\b\x01R\auserIds\"6\n" +
	"\x13GroupCreateResponse\x12\x1f\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\agroupId\"8\n" +
	"\x12GroupDetailRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\"\xdb\x04\n" +
	"\x13GroupDetailResponse\x12\x1f\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\agroupId\x12#\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\tgroupName\x12\x1e\n" +
	"\aprofile\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\aprofile\x12\x1c\n" +
	"\x06avatar\x18\x04 \x01(\tB\x04\xe2A\x01\x02R\x06avatar\x12#\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tB\x04\xe2A\x01\x02R\tcreatedAt\x12#\n" +
	"\n" +
	"is_manager\x18\x06 \x01(\bB\x04\xe2A\x01\x02R\tisManager\x12#\n" +
	"\n" +
	"is_disturb\x18\a \x01(\x05B\x04\xe2A\x01\x02R\tisDisturb\x12#\n" +
	"\n" +
	"visit_card\x18\b \x01(\tB\x04\xe2A\x01\x02R\tvisitCard\x12\x1d\n" +
	"\ais_mute\x18\t \x01(\x05B\x04\xe2A\x01\x02R\x06isMute\x12\x1f\n" +
	"\bis_overt\x18\n" +
	" \x01(\x05B\x04\xe2A\x01\x02R\aisOvert\x127\n" +
	"\x06notice\x18\v \x01(\v2\x1f.web.GroupDetailResponse.NoticeR\x06notice\x12&\n" +
	"\x0fis_allow_invite\x18\f \x01(\x05R\risAllowInvite\x1a\x8a\x01\n" +
	"\x06Notice\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12(\n" +
	"\x10modify_user_name\x18\x05 \x01(\tR\x0emodifyUserName\"<\n" +
	"\x16GroupMemberListRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\"\xd5\x02\n" +
	"\x17GroupMemberListResponse\x12=\n" +
	"\x05items\x18\x01 \x03(\v2!.web.GroupMemberListResponse.ItemB\x04\xe2A\x01\x02R\x05items\x1a\xfa\x01\n" +
	"\x04Item\x12\x1d\n" +
	"\auser_id\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\x06userId\x12 \n" +
	"\bnickname\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\bnickname\x12\x1c\n" +
	"\x06avatar\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\x06avatar\x12\x1c\n" +
	"\x06gender\x18\x04 \x01(\x05B\x04\xe2A\x01\x02R\x06gender\x12\x1c\n" +
	"\x06leader\x18\x05 \x01(\x05B\x04\xe2A\x01\x02R\x06leader\x12\x1d\n" +
	"\ais_mute\x18\x06 \x01(\x05B\x04\xe2A\x01\x02R\x06isMute\x12\x1c\n" +
	"\x06remark\x18\a \x01(\tB\x04\xe2A\x01\x02R\x06remark\x12\x1a\n" +
	"\x05motto\x18\b \x01(\tB\x04\xe2A\x01\x02R\x05motto\"9\n" +
	"\x13GroupDismissRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\"\x16\n" +
	"\x14GroupDismissResponse\"]\n" +
	"\x12GroupInviteRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\x12#\n" +
	"\buser_ids\x18\x02 \x03(\x05B\b\xbaH\x05\x92\x01\x02\b\x01R\auserIds\"\x15\n" +
	"\x13GroupInviteResponse\"=\n" +
	"\x17GetInviteFriendsRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\agroupId\"\xfe\x01\n" +
	"\x18GetInviteFriendsResponse\x12>\n" +
	"\x05items\x18\x01 \x03(\v2\".web.GetInviteFriendsResponse.ItemB\x04\xe2A\x01\x02R\x05items\x1a\xa1\x01\n" +
	"\x04Item\x12\x1d\n" +
	"\auser_id\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\x06userId\x12 \n" +
	"\bnickname\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\bnickname\x12\x1c\n" +
	"\x06avatar\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\x06avatar\x12\x1c\n" +
	"\x06gender\x18\x04 \x01(\x05B\x04\xe2A\x01\x02R\x06gender\x12\x1c\n" +
	"\x06remark\x18\x05 \x01(\tB\x04\xe2A\x01\x02R\x06remark\"8\n" +
	"\x12GroupSecedeRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\"\x15\n" +
	"\x13GroupSecedeResponse\"\x9d\x01\n" +
	"\x13GroupSettingRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\x12&\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tgroupName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\"\n" +
	"\aprofile\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\xff\x01R\aprofile\"\x16\n" +
	"\x14GroupSettingResponse\"V\n" +
	"\x18GroupRemarkUpdateRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\"\x1b\n" +
	"\x19GroupRemarkUpdateResponse\"c\n" +
	"\x18GroupRemoveMemberRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\x12#\n" +
	"\buser_ids\x18\x02 \x03(\x05B\b\xbaH\x05\x92\x01\x02\b\x01R\auserIds\"\x1b\n" +
	"\x19GroupRemoveMemberResponse\"H\n" +
	"\x15GroupOvertListRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\x04page\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8f\x03\n" +
	"\x16GroupOvertListResponse\x12<\n" +
	"\x05items\x18\x01 \x03(\v2 .web.GroupOvertListResponse.ItemB\x04\xe2A\x01\x02R\x05items\x12\x18\n" +
	"\x04next\x18\x02 \x01(\bB\x04\xe2A\x01\x02R\x04next\x1a\x9c\x02\n" +
	"\x04Item\x12\x1f\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\agroupId\x12\x18\n" +
	"\x04type\x18\x02 \x01(\x05B\x04\xe2A\x01\x02R\x04type\x12\x18\n" +
	"\x04name\x18\x03 \x01(\tB\x04\xe2A\x01\x02R\x04name\x12\x1c\n" +
	"\x06avatar\x18\x04 \x01(\tB\x04\xe2A\x01\x02R\x06avatar\x12\x1e\n" +
	"\aprofile\x18\x05 \x01(\tB\x04\xe2A\x01\x02R\aprofile\x12\x1a\n" +
	"\x05count\x18\x06 \x01(\x05B\x04\xe2A\x01\x02R\x05count\x12\x1d\n" +
	"\amax_num\x18\a \x01(\x05B\x04\xe2A\x01\x02R\x06maxNum\x12!\n" +
	"\tis_member\x18\b \x01(\bB\x04\xe2A\x01\x02R\bisMember\x12#\n" +
	"\n" +
	"created_at\x18\t \x01(\tB\x04\xe2A\x01\x02R\tcreatedAt\"\\\n" +
	"\x14GroupHandoverRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\x12 \n" +
	"\auser_id\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\x06userId\"\x17\n" +
	"\x15GroupHandoverResponse\"\x82\x01\n" +
	"\x17GroupAssignAdminRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\x12 \n" +
	"\auser_id\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\x06userId\x12!\n" +
	"\x06action\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x040\x010\x02R\x06action\"\x1a\n" +
	"\x18GroupAssignAdminResponse\"~\n" +
	"\x13GroupNoSpeakRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\x12 \n" +
	"\auser_id\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\x06userId\x12!\n" +
	"\x06action\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x040\x010\x02R\x06action\"\x16\n" +
	"\x14GroupNoSpeakResponse\"Y\n" +
	"\x10GroupMuteRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\x12!\n" +
	"\x06action\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x040\x010\x02R\x06action\"\x13\n" +
	"\x11GroupMuteResponse\"`\n" +
	"\x17GroupAllowInviteRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\x12!\n" +
	"\x06action\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x040\x010\x02R\x06action\"\x1a\n" +
	"\x18GroupAllowInviteResponse\"Z\n" +
	"\x11GroupOvertRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\x12!\n" +
	"\x06action\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x040\x010\x02R\x06action\"\x14\n" +
	"\x12GroupOvertResponse\"8\n" +
	"\x12GroupFakersRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01R\agroupId\"\xbb\x01\n" +
	"\x13GroupFakersResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.web.GroupFakersResponse.ItemR\x05items\x1ao\n" +
	"\x04Item\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar2\x9b\x0f\n" +
	"\x05Group\x12T\n" +
	"\x04List\x12\x15.web.GroupListRequest\x1a\x16.web.GroupListResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/group/list\x12\\\n" +
	"\x06Create\x12\x17.web.GroupCreateRequest\x1a\x18.web.GroupCreateResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/group/create\x12\\\n" +
	"\x06Detail\x12\x17.web.GroupDetailRequest\x1a\x18.web.GroupDetailResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/group/detail\x12m\n" +
	"\n" +
	"MemberList\x12\x1b.web.GroupMemberListRequest\x1a\x1c.web.GroupMemberListResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/group/member-list\x12`\n" +
	"\aDismiss\x12\x18.web.GroupDismissRequest\x1a\x19.web.GroupDismissResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/group/dismiss\x12\\\n" +
	"\x06Invite\x12\x17.web.GroupInviteRequest\x1a\x18.web.GroupInviteResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/group/invite\x12|\n" +
	"\x10GetInviteFriends\x12\x1c.web.GetInviteFriendsRequest\x1a\x1d.web.GetInviteFriendsResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/group/get-invite-friends\x12\\\n" +
	"\x06Secede\x12\x17.web.GroupSecedeRequest\x1a\x18.web.GroupSecedeResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/group/secede\x12`\n" +
	"\aSetting\x12\x18.web.GroupSettingRequest\x1a\x19.web.GroupSettingResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/group/setting\x12u\n" +
	"\fRemarkUpdate\x12\x1d.web.GroupRemarkUpdateRequest\x1a\x1e.web.GroupRemarkUpdateResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/group/remark-update\x12u\n" +
	"\fRemoveMember\x12\x1d.web.GroupRemoveMemberRequest\x1a\x1e.web.GroupRemoveMemberResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/group/remove-member\x12i\n" +
	"\tOvertList\x12\x1a.web.GroupOvertListRequest\x1a\x1b.web.GroupOvertListResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/group/overt-list\x12d\n" +
	"\bHandover\x12\x19.web.GroupHandoverRequest\x1a\x1a.web.GroupHandoverResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/group/handover\x12q\n" +
	"\vAssignAdmin\x12\x1c.web.GroupAssignAdminRequest\x1a\x1d.web.GroupAssignAdminResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v1/group/assign-admin\x12a\n" +
	"\aNoSpeak\x12\x18.web.GroupNoSpeakRequest\x1a\x19.web.GroupNoSpeakResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/group/no-speak\x12T\n" +
	"\x04Mute\x12\x15.web.GroupMuteRequest\x1a\x16.web.GroupMuteResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/group/mute\x12p\n" +
	"\vAllowInvite\x12\x1c.web.GroupAllowInviteRequest\x1a\x1d.web.GroupAllowInviteResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/group/allowInvite\x12X\n" +
	"\x05Overt\x12\x16.web.GroupOvertRequest\x1a\x17.web.GroupOvertResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/group/overt\x12\\\n" +
	"\x06Fakers\x12\x17.web.GroupFakersRequest\x1a\x18.web.GroupFakersResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/group/fakersB\fZ\n" +
	"web/v1;webb\x06proto3"

var (
	file_web_v1_group_proto_rawDescOnce sync.Once
	file_web_v1_group_proto_rawDescData []byte
)

func file_web_v1_group_proto_rawDescGZIP() []byte {
	file_web_v1_group_proto_rawDescOnce.Do(func() {
		file_web_v1_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_v1_group_proto_rawDesc), len(file_web_v1_group_proto_rawDesc)))
	})
	return file_web_v1_group_proto_rawDescData
}

var file_web_v1_group_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_web_v1_group_proto_goTypes = []any{
	(*GroupListRequest)(nil),              // 0: web.GroupListRequest
	(*GroupListResponse)(nil),             // 1: web.GroupListResponse
	(*GroupCreateRequest)(nil),            // 2: web.GroupCreateRequest
	(*GroupCreateResponse)(nil),           // 3: web.GroupCreateResponse
	(*GroupDetailRequest)(nil),            // 4: web.GroupDetailRequest
	(*GroupDetailResponse)(nil),           // 5: web.GroupDetailResponse
	(*GroupMemberListRequest)(nil),        // 6: web.GroupMemberListRequest
	(*GroupMemberListResponse)(nil),       // 7: web.GroupMemberListResponse
	(*GroupDismissRequest)(nil),           // 8: web.GroupDismissRequest
	(*GroupDismissResponse)(nil),          // 9: web.GroupDismissResponse
	(*GroupInviteRequest)(nil),            // 10: web.GroupInviteRequest
	(*GroupInviteResponse)(nil),           // 11: web.GroupInviteResponse
	(*GetInviteFriendsRequest)(nil),       // 12: web.GetInviteFriendsRequest
	(*GetInviteFriendsResponse)(nil),      // 13: web.GetInviteFriendsResponse
	(*GroupSecedeRequest)(nil),            // 14: web.GroupSecedeRequest
	(*GroupSecedeResponse)(nil),           // 15: web.GroupSecedeResponse
	(*GroupSettingRequest)(nil),           // 16: web.GroupSettingRequest
	(*GroupSettingResponse)(nil),          // 17: web.GroupSettingResponse
	(*GroupRemarkUpdateRequest)(nil),      // 18: web.GroupRemarkUpdateRequest
	(*GroupRemarkUpdateResponse)(nil),     // 19: web.GroupRemarkUpdateResponse
	(*GroupRemoveMemberRequest)(nil),      // 20: web.GroupRemoveMemberRequest
	(*GroupRemoveMemberResponse)(nil),     // 21: web.GroupRemoveMemberResponse
	(*GroupOvertListRequest)(nil),         // 22: web.GroupOvertListRequest
	(*GroupOvertListResponse)(nil),        // 23: web.GroupOvertListResponse
	(*GroupHandoverRequest)(nil),          // 24: web.GroupHandoverRequest
	(*GroupHandoverResponse)(nil),         // 25: web.GroupHandoverResponse
	(*GroupAssignAdminRequest)(nil),       // 26: web.GroupAssignAdminRequest
	(*GroupAssignAdminResponse)(nil),      // 27: web.GroupAssignAdminResponse
	(*GroupNoSpeakRequest)(nil),           // 28: web.GroupNoSpeakRequest
	(*GroupNoSpeakResponse)(nil),          // 29: web.GroupNoSpeakResponse
	(*GroupMuteRequest)(nil),              // 30: web.GroupMuteRequest
	(*GroupMuteResponse)(nil),             // 31: web.GroupMuteResponse
	(*GroupAllowInviteRequest)(nil),       // 32: web.GroupAllowInviteRequest
	(*GroupAllowInviteResponse)(nil),      // 33: web.GroupAllowInviteResponse
	(*GroupOvertRequest)(nil),             // 34: web.GroupOvertRequest
	(*GroupOvertResponse)(nil),            // 35: web.GroupOvertResponse
	(*GroupFakersRequest)(nil),            // 36: web.GroupFakersRequest
	(*GroupFakersResponse)(nil),           // 37: web.GroupFakersResponse
	(*GroupListResponse_Item)(nil),        // 38: web.GroupListResponse.Item
	(*GroupDetailResponse_Notice)(nil),    // 39: web.GroupDetailResponse.Notice
	(*GroupMemberListResponse_Item)(nil),  // 40: web.GroupMemberListResponse.Item
	(*GetInviteFriendsResponse_Item)(nil), // 41: web.GetInviteFriendsResponse.Item
	(*GroupOvertListResponse_Item)(nil),   // 42: web.GroupOvertListResponse.Item
	(*GroupFakersResponse_Item)(nil),      // 43: web.GroupFakersResponse.Item
}
var file_web_v1_group_proto_depIdxs = []int32{
	38, // 0: web.GroupListResponse.items:type_name -> web.GroupListResponse.Item
	39, // 1: web.GroupDetailResponse.notice:type_name -> web.GroupDetailResponse.Notice
	40, // 2: web.GroupMemberListResponse.items:type_name -> web.GroupMemberListResponse.Item
	41, // 3: web.GetInviteFriendsResponse.items:type_name -> web.GetInviteFriendsResponse.Item
	42, // 4: web.GroupOvertListResponse.items:type_name -> web.GroupOvertListResponse.Item
	43, // 5: web.GroupFakersResponse.items:type_name -> web.GroupFakersResponse.Item
	0,  // 6: web.Group.List:input_type -> web.GroupListRequest
	2,  // 7: web.Group.Create:input_type -> web.GroupCreateRequest
	4,  // 8: web.Group.Detail:input_type -> web.GroupDetailRequest
	6,  // 9: web.Group.MemberList:input_type -> web.GroupMemberListRequest
	8,  // 10: web.Group.Dismiss:input_type -> web.GroupDismissRequest
	10, // 11: web.Group.Invite:input_type -> web.GroupInviteRequest
	12, // 12: web.Group.GetInviteFriends:input_type -> web.GetInviteFriendsRequest
	14, // 13: web.Group.Secede:input_type -> web.GroupSecedeRequest
	16, // 14: web.Group.Setting:input_type -> web.GroupSettingRequest
	18, // 15: web.Group.RemarkUpdate:input_type -> web.GroupRemarkUpdateRequest
	20, // 16: web.Group.RemoveMember:input_type -> web.GroupRemoveMemberRequest
	22, // 17: web.Group.OvertList:input_type -> web.GroupOvertListRequest
	24, // 18: web.Group.Handover:input_type -> web.GroupHandoverRequest
	26, // 19: web.Group.AssignAdmin:input_type -> web.GroupAssignAdminRequest
	28, // 20: web.Group.NoSpeak:input_type -> web.GroupNoSpeakRequest
	30, // 21: web.Group.Mute:input_type -> web.GroupMuteRequest
	32, // 22: web.Group.AllowInvite:input_type -> web.GroupAllowInviteRequest
	34, // 23: web.Group.Overt:input_type -> web.GroupOvertRequest
	36, // 24: web.Group.Fakers:input_type -> web.GroupFakersRequest
	1,  // 25: web.Group.List:output_type -> web.GroupListResponse
	3,  // 26: web.Group.Create:output_type -> web.GroupCreateResponse
	5,  // 27: web.Group.Detail:output_type -> web.GroupDetailResponse
	7,  // 28: web.Group.MemberList:output_type -> web.GroupMemberListResponse
	9,  // 29: web.Group.Dismiss:output_type -> web.GroupDismissResponse
	11, // 30: web.Group.Invite:output_type -> web.GroupInviteResponse
	13, // 31: web.Group.GetInviteFriends:output_type -> web.GetInviteFriendsResponse
	15, // 32: web.Group.Secede:output_type -> web.GroupSecedeResponse
	17, // 33: web.Group.Setting:output_type -> web.GroupSettingResponse
	19, // 34: web.Group.RemarkUpdate:output_type -> web.GroupRemarkUpdateResponse
	21, // 35: web.Group.RemoveMember:output_type -> web.GroupRemoveMemberResponse
	23, // 36: web.Group.OvertList:output_type -> web.GroupOvertListResponse
	25, // 37: web.Group.Handover:output_type -> web.GroupHandoverResponse
	27, // 38: web.Group.AssignAdmin:output_type -> web.GroupAssignAdminResponse
	29, // 39: web.Group.NoSpeak:output_type -> web.GroupNoSpeakResponse
	31, // 40: web.Group.Mute:output_type -> web.GroupMuteResponse
	33, // 41: web.Group.AllowInvite:output_type -> web.GroupAllowInviteResponse
	35, // 42: web.Group.Overt:output_type -> web.GroupOvertResponse
	37, // 43: web.Group.Fakers:output_type -> web.GroupFakersResponse
	25, // [25:44] is the sub-list for method output_type
	6,  // [6:25] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_web_v1_group_proto_init() }
func file_web_v1_group_proto_init() {
	if File_web_v1_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_v1_group_proto_rawDesc), len(file_web_v1_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_v1_group_proto_goTypes,
		DependencyIndexes: file_web_v1_group_proto_depIdxs,
		MessageInfos:      file_web_v1_group_proto_msgTypes,
	}.Build()
	File_web_v1_group_proto = out.File
	file_web_v1_group_proto_goTypes = nil
	file_web_v1_group_proto_depIdxs = nil
}
