// Code generated by protoc-gen-bff. DO NOT EDIT.
// Version: 1.0.0

package web

import (
	"context"

	"github.com/gin-gonic/gin"
)

// IInviteHandler BFF 接口
type IInviteHandler interface {

	// 生成邀请码
	GenerateInviteCode(ctx context.Context, in *InviteGenerateRequest) (*InviteGenerateResponse, error)
	// 获取我的邀请码列表
	GetMyInviteCodes(ctx context.Context, in *InviteListRequest) (*InviteListResponse, error)
	// 获取邀请统计
	GetInviteStats(ctx context.Context, in *InviteStatsRequest) (*InviteStatsResponse, error)
	// 禁用邀请码
	DisableInviteCode(ctx context.Context, in *InviteDisableRequest) (*InviteDisableResponse, error)
	// 我邀请注册的好友列表（users.invite_user_id = 当前用户）
	ListInviteFriends(ctx context.Context, in *InviteFriendListRequest) (*InviteFriendListResponse, error)
}

// RegisterInviteHandler 注册服务路由处理器
func RegisterInviteHandler(r gin.IRoutes, interceptor interface {
	ShouldProto(c *gin.Context, in any) error
	Do(fn func(ctx *gin.Context) (any, error)) func(c *gin.Context)
}, handler IInviteHandler) {
	if interceptor == nil {
		panic("interceptor is nil")
	}

	if handler == nil {
		panic("handler is nil")
	}

	r.POST("/api/v1/invite/generate", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in InviteGenerateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.GenerateInviteCode(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/invite/list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in InviteListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.GetMyInviteCodes(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/invite/stats", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in InviteStatsRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.GetInviteStats(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/invite/disable", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in InviteDisableRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.DisableInviteCode(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/invite/friends", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in InviteFriendListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.ListInviteFriends(ctx.Request.Context(), &in)
	}))

}
