// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: web/v1/invite.proto

package web

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InviteCodeGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteCodeGetRequest) Reset() {
	*x = InviteCodeGetRequest{}
	mi := &file_web_v1_invite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteCodeGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteCodeGetRequest) ProtoMessage() {}

func (x *InviteCodeGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_invite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteCodeGetRequest.ProtoReflect.Descriptor instead.
func (*InviteCodeGetRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_invite_proto_rawDescGZIP(), []int{0}
}

type InviteCodeGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteCodeGetResponse) Reset() {
	*x = InviteCodeGetResponse{}
	mi := &file_web_v1_invite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteCodeGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteCodeGetResponse) ProtoMessage() {}

func (x *InviteCodeGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_invite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteCodeGetResponse.ProtoReflect.Descriptor instead.
func (*InviteCodeGetResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_invite_proto_rawDescGZIP(), []int{1}
}

func (x *InviteCodeGetResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 获取邀请统计请求
type InviteStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteStatsRequest) Reset() {
	*x = InviteStatsRequest{}
	mi := &file_web_v1_invite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteStatsRequest) ProtoMessage() {}

func (x *InviteStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_invite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteStatsRequest.ProtoReflect.Descriptor instead.
func (*InviteStatsRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_invite_proto_rawDescGZIP(), []int{2}
}

// 获取邀请统计响应
type InviteStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalInvitations int32                  `protobuf:"varint,1,opt,name=total_invitations,json=totalInvitations,proto3" json:"total_invitations,omitempty"` // 总邀请人数
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InviteStatsResponse) Reset() {
	*x = InviteStatsResponse{}
	mi := &file_web_v1_invite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteStatsResponse) ProtoMessage() {}

func (x *InviteStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_invite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteStatsResponse.ProtoReflect.Descriptor instead.
func (*InviteStatsResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_invite_proto_rawDescGZIP(), []int{3}
}

func (x *InviteStatsResponse) GetTotalInvitations() int32 {
	if x != nil {
		return x.TotalInvitations
	}
	return 0
}

// 邀请好友列表请求
type InviteFriendListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 页码，从 1 开始；未传或 0 时服务端按 1 处理
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// 每页条数；未传或 0 时默认 20，最大 100
	PageSize      int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteFriendListRequest) Reset() {
	*x = InviteFriendListRequest{}
	mi := &file_web_v1_invite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteFriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteFriendListRequest) ProtoMessage() {}

func (x *InviteFriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_invite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteFriendListRequest.ProtoReflect.Descriptor instead.
func (*InviteFriendListRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_invite_proto_rawDescGZIP(), []int{4}
}

func (x *InviteFriendListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *InviteFriendListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 邀请好友列表响应
type InviteFriendListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Items []*InviteFriendItem    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// 符合条件的总条数（用于分页）
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteFriendListResponse) Reset() {
	*x = InviteFriendListResponse{}
	mi := &file_web_v1_invite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteFriendListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteFriendListResponse) ProtoMessage() {}

func (x *InviteFriendListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_invite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteFriendListResponse.ProtoReflect.Descriptor instead.
func (*InviteFriendListResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_invite_proto_rawDescGZIP(), []int{5}
}

func (x *InviteFriendListResponse) GetItems() []*InviteFriendItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *InviteFriendListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 被邀请注册的好友（简要信息）
type InviteFriendItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // users.id
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Mobile        string                 `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`                        // 脱敏展示
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`                          // 脱敏展示
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 注册时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteFriendItem) Reset() {
	*x = InviteFriendItem{}
	mi := &file_web_v1_invite_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteFriendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteFriendItem) ProtoMessage() {}

func (x *InviteFriendItem) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_invite_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteFriendItem.ProtoReflect.Descriptor instead.
func (*InviteFriendItem) Descriptor() ([]byte, []int) {
	return file_web_v1_invite_proto_rawDescGZIP(), []int{6}
}

func (x *InviteFriendItem) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InviteFriendItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *InviteFriendItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *InviteFriendItem) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *InviteFriendItem) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteFriendItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_web_v1_invite_proto protoreflect.FileDescriptor

const file_web_v1_invite_proto_rawDesc = "" +
	"\n" +
	"\x13web/v1/invite.proto\x12\x03web\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"\x16\n" +
	"\x14InviteCodeGetRequest\"1\n" +
	"\x15InviteCodeGetResponse\x12\x18\n" +
	"\x04code\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\x04code\"\x14\n" +
	"\x12InviteStatsRequest\"B\n" +
	"\x13InviteStatsResponse\x12+\n" +
	"\x11total_invitations\x18\x01 \x01(\x05R\x10totalInvitations\"J\n" +
	"\x17InviteFriendListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"c\n" +
	"\x18InviteFriendListResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.web.InviteFriendItemR\x05items\x12\x1a\n" +
	"\x05total\x18\x02 \x01(\x05B\x04\xe2A\x01\x02R\x05total\"\xb2\x01\n" +
	"\x10InviteFriendItem\x12\x1d\n" +
	"\auser_id\x18\x01 \x01(\x05B\x04\xe2A\x01\x02R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06mobile\x18\x04 \x01(\tR\x06mobile\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt2\xcd\x02\n" +
	"\x06Invite\x12h\n" +
	"\x0fGetMyInviteCode\x12\x19.web.InviteCodeGetRequest\x1a\x1a.web.InviteCodeGetResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/invite/code\x12d\n" +
	"\x0eGetInviteStats\x12\x17.web.InviteStatsRequest\x1a\x18.web.InviteStatsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/invite/stats\x12s\n" +
	"\x11ListInviteFriends\x12\x1c.web.InviteFriendListRequest\x1a\x1d.web.InviteFriendListResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/invite/friendsB\fZ\n" +
	"web/v1;webb\x06proto3"

var (
	file_web_v1_invite_proto_rawDescOnce sync.Once
	file_web_v1_invite_proto_rawDescData []byte
)

func file_web_v1_invite_proto_rawDescGZIP() []byte {
	file_web_v1_invite_proto_rawDescOnce.Do(func() {
		file_web_v1_invite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_v1_invite_proto_rawDesc), len(file_web_v1_invite_proto_rawDesc)))
	})
	return file_web_v1_invite_proto_rawDescData
}

var file_web_v1_invite_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_web_v1_invite_proto_goTypes = []any{
	(*InviteCodeGetRequest)(nil),     // 0: web.InviteCodeGetRequest
	(*InviteCodeGetResponse)(nil),    // 1: web.InviteCodeGetResponse
	(*InviteStatsRequest)(nil),       // 2: web.InviteStatsRequest
	(*InviteStatsResponse)(nil),      // 3: web.InviteStatsResponse
	(*InviteFriendListRequest)(nil),  // 4: web.InviteFriendListRequest
	(*InviteFriendListResponse)(nil), // 5: web.InviteFriendListResponse
	(*InviteFriendItem)(nil),         // 6: web.InviteFriendItem
}
var file_web_v1_invite_proto_depIdxs = []int32{
	6, // 0: web.InviteFriendListResponse.items:type_name -> web.InviteFriendItem
	0, // 1: web.Invite.GetMyInviteCode:input_type -> web.InviteCodeGetRequest
	2, // 2: web.Invite.GetInviteStats:input_type -> web.InviteStatsRequest
	4, // 3: web.Invite.ListInviteFriends:input_type -> web.InviteFriendListRequest
	1, // 4: web.Invite.GetMyInviteCode:output_type -> web.InviteCodeGetResponse
	3, // 5: web.Invite.GetInviteStats:output_type -> web.InviteStatsResponse
	5, // 6: web.Invite.ListInviteFriends:output_type -> web.InviteFriendListResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_web_v1_invite_proto_init() }
func file_web_v1_invite_proto_init() {
	if File_web_v1_invite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_v1_invite_proto_rawDesc), len(file_web_v1_invite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_v1_invite_proto_goTypes,
		DependencyIndexes: file_web_v1_invite_proto_depIdxs,
		MessageInfos:      file_web_v1_invite_proto_msgTypes,
	}.Build()
	File_web_v1_invite_proto = out.File
	file_web_v1_invite_proto_goTypes = nil
	file_web_v1_invite_proto_depIdxs = nil
}
