// Code generated by protoc-gen-bff. DO NOT EDIT.
// Version: 1.0.0

package web

import (
	"context"

	"github.com/gin-gonic/gin"
)

// INoticeHandler BFF 接口
type INoticeHandler interface {

	// 系统通知列表（按时间倒序，默认每页 15 条）
	ListNotice(ctx context.Context, in *NoticeListRequest) (*NoticeListResponse, error)
	// 未读通知数
	GetUnreadCount(ctx context.Context, in *NoticeUnreadCountRequest) (*NoticeUnreadCountResponse, error)
	// 清除未读（全部标记为已读）
	ClearUnread(ctx context.Context, in *NoticeClearUnreadRequest) (*NoticeClearUnreadResponse, error)
	// 获取通知文章（notice_article，仅 status=开启）
	GetNoticeArticle(ctx context.Context, in *NoticeArticleGetRequest) (*NoticeArticleGetResponse, error)
}

// RegisterNoticeHandler 注册服务路由处理器
func RegisterNoticeHandler(r gin.IRoutes, interceptor interface {
	ShouldProto(c *gin.Context, in any) error
	Do(fn func(ctx *gin.Context) (any, error)) func(c *gin.Context)
}, handler INoticeHandler) {
	if interceptor == nil {
		panic("interceptor is nil")
	}

	if handler == nil {
		panic("handler is nil")
	}

	r.POST("/api/v1/notice/list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in NoticeListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.ListNotice(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/notice/unread-count", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in NoticeUnreadCountRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.GetUnreadCount(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/notice/clear-unread", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in NoticeClearUnreadRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.ClearUnread(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/notice/article", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in NoticeArticleGetRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.GetNoticeArticle(ctx.Request.Context(), &in)
	}))

}
