// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: web/v1/sts.proto

package web

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取COS临时密钥请求参数
type GetCosSTSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"` // 文件名
	FileType      string                 `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"` // 文件类型 (image, video, file)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCosSTSRequest) Reset() {
	*x = GetCosSTSRequest{}
	mi := &file_web_v1_sts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCosSTSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCosSTSRequest) ProtoMessage() {}

func (x *GetCosSTSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_sts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCosSTSRequest.ProtoReflect.Descriptor instead.
func (*GetCosSTSRequest) Descriptor() ([]byte, []int) {
	return file_web_v1_sts_proto_rawDescGZIP(), []int{0}
}

func (x *GetCosSTSRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetCosSTSRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

// 获取COS临时密钥响应参数
type GetCosSTSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TmpSecretId   string                 `protobuf:"bytes,1,opt,name=tmp_secret_id,json=tmpSecretId,proto3" json:"tmp_secret_id,omitempty"`    // 临时密钥 ID
	TmpSecretKey  string                 `protobuf:"bytes,2,opt,name=tmp_secret_key,json=tmpSecretKey,proto3" json:"tmp_secret_key,omitempty"` // 临时密钥 Key
	SessionToken  string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`   // 临时密钥 Token
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`                                   // COS区域
	Bucket        string                 `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`                                   // Bucket名称
	Key           string                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`                                         // 对象路径(文件在COS中的完整路径)
	StartTime     int64                  `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`           // 临时密钥生效时间(Unix时间戳)
	ExpiredTime   int64                  `protobuf:"varint,8,opt,name=expired_time,json=expiredTime,proto3" json:"expired_time,omitempty"`     // 临时密钥过期时间(Unix时间戳)
	PresignedUrl  string                 `protobuf:"bytes,9,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`   // 预签名PUT URL(客户端可直接PUT上传)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCosSTSResponse) Reset() {
	*x = GetCosSTSResponse{}
	mi := &file_web_v1_sts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCosSTSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCosSTSResponse) ProtoMessage() {}

func (x *GetCosSTSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_sts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCosSTSResponse.ProtoReflect.Descriptor instead.
func (*GetCosSTSResponse) Descriptor() ([]byte, []int) {
	return file_web_v1_sts_proto_rawDescGZIP(), []int{1}
}

func (x *GetCosSTSResponse) GetTmpSecretId() string {
	if x != nil {
		return x.TmpSecretId
	}
	return ""
}

func (x *GetCosSTSResponse) GetTmpSecretKey() string {
	if x != nil {
		return x.TmpSecretKey
	}
	return ""
}

func (x *GetCosSTSResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *GetCosSTSResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetCosSTSResponse) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GetCosSTSResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetCosSTSResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetCosSTSResponse) GetExpiredTime() int64 {
	if x != nil {
		return x.ExpiredTime
	}
	return 0
}

func (x *GetCosSTSResponse) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

var File_web_v1_sts_proto protoreflect.FileDescriptor

const file_web_v1_sts_proto_rawDesc = "" +
	"\n" +
	"\x10web/v1/sts.proto\x12\x03web\x1a\x1bbuf/validate/validate.proto\"U\n" +
	"\x10GetCosSTSRequest\x12$\n" +
	"\tfile_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x02 \x01(\tR\bfileType\"\xab\x02\n" +
	"\x11GetCosSTSResponse\x12\"\n" +
	"\rtmp_secret_id\x18\x01 \x01(\tR\vtmpSecretId\x12$\n" +
	"\x0etmp_secret_key\x18\x02 \x01(\tR\ftmpSecretKey\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x16\n" +
	"\x06bucket\x18\x05 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x06 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x03R\tstartTime\x12!\n" +
	"\fexpired_time\x18\b \x01(\x03R\vexpiredTime\x12#\n" +
	"\rpresigned_url\x18\t \x01(\tR\fpresignedUrlB\fZ\n" +
	"web/v1;webb\x06proto3"

var (
	file_web_v1_sts_proto_rawDescOnce sync.Once
	file_web_v1_sts_proto_rawDescData []byte
)

func file_web_v1_sts_proto_rawDescGZIP() []byte {
	file_web_v1_sts_proto_rawDescOnce.Do(func() {
		file_web_v1_sts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_v1_sts_proto_rawDesc), len(file_web_v1_sts_proto_rawDesc)))
	})
	return file_web_v1_sts_proto_rawDescData
}

var file_web_v1_sts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_web_v1_sts_proto_goTypes = []any{
	(*GetCosSTSRequest)(nil),  // 0: web.GetCosSTSRequest
	(*GetCosSTSResponse)(nil), // 1: web.GetCosSTSResponse
}
var file_web_v1_sts_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_web_v1_sts_proto_init() }
func file_web_v1_sts_proto_init() {
	if File_web_v1_sts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_v1_sts_proto_rawDesc), len(file_web_v1_sts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_web_v1_sts_proto_goTypes,
		DependencyIndexes: file_web_v1_sts_proto_depIdxs,
		MessageInfos:      file_web_v1_sts_proto_msgTypes,
	}.Build()
	File_web_v1_sts_proto = out.File
	file_web_v1_sts_proto_goTypes = nil
	file_web_v1_sts_proto_depIdxs = nil
}
