// Code generated by protoc-gen-bff. DO NOT EDIT.
// Version: 1.0.0

package web

import (
	"context"

	"github.com/gin-gonic/gin"
)

// IUserHandler BFF 接口
type IUserHandler interface {

	// 获取登录用户详情接口
	Detail(ctx context.Context, in *UserDetailRequest) (*UserDetailResponse, error)
	// 获取用户配置信息接口
	Setting(ctx context.Context, in *UserSettingRequest) (*UserSettingResponse, error)
	// 更新用户信息接口
	DetailUpdate(ctx context.Context, in *UserDetailUpdateRequest) (*UserDetailUpdateResponse, error)
	// 更新用户密码接口
	PasswordUpdate(ctx context.Context, in *UserPasswordUpdateRequest) (*UserPasswordUpdateResponse, error)
	// 更新用户手机号接口
	MobileUpdate(ctx context.Context, in *UserMobileUpdateRequest) (*UserMobileUpdateResponse, error)
	// 更新用户邮箱接口
	EmailUpdate(ctx context.Context, in *UserEmailUpdateRequest) (*UserEmailUpdateResponse, error)
	// 商户入驻申请
	MerchantApply(ctx context.Context, in *UserMerchantApplyRequest) (*UserMerchantApplyResponse, error)
	// 查询本人最近一次商户申请状态
	MerchantStatus(ctx context.Context, in *UserMerchantStatusRequest) (*UserMerchantStatusResponse, error)
	// 获取本人商户资料（供查看/编辑表单回填，字段与 merchant 表一致）
	MerchantProfile(ctx context.Context, in *UserMerchantProfileRequest) (*UserMerchantStatusResponse, error)
	// 发布商户挂售任务
	MerchantTaskCreate(ctx context.Context, in *UserMerchantTaskCreateRequest) (*UserMerchantTaskCreateResponse, error)
	// 本人商户任务列表
	MerchantTaskMyList(ctx context.Context, in *UserMerchantTaskMyListRequest) (*UserMerchantTaskListResponse, error)
	// 全平台：已上架且待交易的任务列表
	MerchantTaskMarketList(ctx context.Context, in *UserMerchantTaskMarketListRequest) (*UserMerchantTaskListResponse, error)
	// 任务详情（按 id）
	MerchantTaskDetail(ctx context.Context, in *UserMerchantTaskDetailRequest) (*UserMerchantTaskItem, error)
	// 修改自己的任务（仅待交易且未删除）
	MerchantTaskUpdate(ctx context.Context, in *UserMerchantTaskUpdateRequest) (*UserMerchantTaskUpdateResponse, error)
	// 上架自己的任务
	MerchantTaskUp(ctx context.Context, in *UserMerchantTaskIdRequest) (*UserMerchantTaskActionResponse, error)
	// 下架自己的任务
	MerchantTaskDown(ctx context.Context, in *UserMerchantTaskIdRequest) (*UserMerchantTaskActionResponse, error)
	// 结束自己的任务（软删除，不再展示）
	MerchantTaskFinish(ctx context.Context, in *UserMerchantTaskIdRequest) (*UserMerchantTaskActionResponse, error)
	// 商户收款方式：创建
	MerchantPaytypeCreate(ctx context.Context, in *UserMerchantPaytypeCreateRequest) (*UserMerchantPaytypeCreateResponse, error)
	// 商户收款方式：编辑
	MerchantPaytypeUpdate(ctx context.Context, in *UserMerchantPaytypeUpdateRequest) (*UserMerchantPaytypeUpdateResponse, error)
	// 商户收款方式：列表（本人全部，含已作废，不分页）
	MerchantPaytypeList(ctx context.Context, in *UserMerchantPaytypeListRequest) (*UserMerchantPaytypeListResponse, error)
	// 商户收款方式：作废
	MerchantPaytypeInvalidate(ctx context.Context, in *UserMerchantPaytypeInvalidateRequest) (*UserMerchantPaytypeInvalidateResponse, error)
	// 商户订单：创建（整单购买，挂单变为交易中）
	MerchantOrderCreate(ctx context.Context, in *UserMerchantOrderCreateRequest) (*UserMerchantOrderCreateResponse, error)

	MerchantOrderDetail(ctx context.Context, in *UserMerchantOrderDetailRequest) (*UserMerchantOrderItem, error)

	MerchantOrderCancel(ctx context.Context, in *UserMerchantOrderCancelRequest) (*UserMerchantOrderActionResponse, error)

	MerchantOrderList(ctx context.Context, in *UserMerchantOrderListRequest) (*UserMerchantOrderListResponse, error)

	MerchantOrderConfirmPay(ctx context.Context, in *UserMerchantOrderConfirmPayRequest) (*UserMerchantOrderActionResponse, error)

	MerchantOrderUrge(ctx context.Context, in *UserMerchantOrderIdRequest) (*UserMerchantOrderActionResponse, error)

	MerchantOrderAppealSeller(ctx context.Context, in *UserMerchantOrderAppealRequest) (*UserMerchantOrderActionResponse, error)

	MerchantOrderAppealBuyer(ctx context.Context, in *UserMerchantOrderAppealRequest) (*UserMerchantOrderActionResponse, error)
	// 商户订单 C2C 对话：发消息（首条自动建 merchant_session，WebSocket event: im.message.c2c）
	MerchantChatSend(ctx context.Context, in *UserMerchantChatSendRequest) (*UserMerchantChatSendResponse, error)

	MerchantChatUnread(ctx context.Context, in *UserMerchantChatUnreadRequest) (*UserMerchantChatUnreadResponse, error)

	MerchantChatSessionList(ctx context.Context, in *UserMerchantChatSessionListRequest) (*UserMerchantChatSessionListResponse, error)

	MerchantChatMessageList(ctx context.Context, in *UserMerchantChatMessageListRequest) (*UserMerchantChatMessageListResponse, error)
	// 清除某商户会话未读（与 talk_mode=3、Redis im:unread 键一致；入参 receiver_id 为 session_id）
	MerchantChatClearUnread(ctx context.Context, in *UserMerchantChatClearUnreadRequest) (*UserMerchantChatClearUnreadResponse, error)
}

// RegisterUserHandler 注册服务路由处理器
func RegisterUserHandler(r gin.IRoutes, interceptor interface {
	ShouldProto(c *gin.Context, in any) error
	Do(fn func(ctx *gin.Context) (any, error)) func(c *gin.Context)
}, handler IUserHandler) {
	if interceptor == nil {
		panic("interceptor is nil")
	}

	if handler == nil {
		panic("handler is nil")
	}

	r.POST("/api/v1/user/detail", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserDetailRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Detail(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/user/setting", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserSettingRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.Setting(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/user/detail-update", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserDetailUpdateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.DetailUpdate(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/user/password-update", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserPasswordUpdateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.PasswordUpdate(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/user/mobile-update", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMobileUpdateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MobileUpdate(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/user/email-update", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserEmailUpdateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.EmailUpdate(ctx.Request.Context(), &in)
	}))

	merchantApply := func(ctx *gin.Context) (any, error) {
		var in UserMerchantApplyRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}
		return handler.MerchantApply(ctx.Request.Context(), &in)
	}
	r.POST("/api/v1/merchant/apply", interceptor.Do(merchantApply))
	r.POST("/api/v1/user/merchant-apply", interceptor.Do(merchantApply))

	r.POST("/api/v1/merchant/status", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantStatusRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantStatus(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/profile", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantProfileRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantProfile(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/task/create", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantTaskCreateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantTaskCreate(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/task/my-list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantTaskMyListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantTaskMyList(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/task/market-list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantTaskMarketListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantTaskMarketList(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/task/detail", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantTaskDetailRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantTaskDetail(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/task/update", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantTaskUpdateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantTaskUpdate(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/task/up", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantTaskIdRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantTaskUp(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/task/down", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantTaskIdRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantTaskDown(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/task/finish", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantTaskIdRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantTaskFinish(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/paytype/create", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantPaytypeCreateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantPaytypeCreate(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/paytype/update", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantPaytypeUpdateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantPaytypeUpdate(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/paytype/list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantPaytypeListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantPaytypeList(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/paytype/invalidate", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantPaytypeInvalidateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantPaytypeInvalidate(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/order/create", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantOrderCreateRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantOrderCreate(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/order/detail", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantOrderDetailRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantOrderDetail(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/order/cancel", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantOrderCancelRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantOrderCancel(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/order/list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantOrderListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantOrderList(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/order/confirm-pay", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantOrderConfirmPayRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantOrderConfirmPay(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/order/urge", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantOrderIdRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantOrderUrge(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/order/appeal-seller", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantOrderAppealRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantOrderAppealSeller(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/order/appeal-buyer", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantOrderAppealRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantOrderAppealBuyer(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/chat/send", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantChatSendRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantChatSend(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/chat/unread", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantChatUnreadRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantChatUnread(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/chat/session-list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantChatSessionListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantChatSessionList(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/chat/message-list", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantChatMessageListRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantChatMessageList(ctx.Request.Context(), &in)
	}))

	r.POST("/api/v1/merchant/chat/clear-unread", interceptor.Do(func(ctx *gin.Context) (any, error) {
		var in UserMerchantChatClearUnreadRequest
		if err := interceptor.ShouldProto(ctx, &in); err != nil {
			return nil, err
		}

		return handler.MerchantChatClearUnread(ctx.Request.Context(), &in)
	}))

}
