package repo

import (
	"github.com/google/wire"
)

var ProviderSet = wire.NewSet(
	NewSource,
	NewContact,
	NewContactGroup,
	NewGroupMember,
	NewUsers,
	NewGroup,
	NewGroupApply,
	NewTalkRecordGroup,
	NewTalkRecordFriend,
	NewGroupNotice,
	NewTalkSession,
	NewTalkRecordGroupDel,
	NewTalkGroupMsgReader,
	NewEmoticon,
	NewGroupVote,
	NewFileUpload,
	NewArticleClass,
	NewArticle,
	NewArticleHistory,
	NewArticleAnnex,
	NewDepartment,
	NewOrganize,
	NewPosition,
	NewRobot,
	NewAdmin,
	NewOAuthUsers,
	NewSysRole,
	NewSysResource,
	NewSysMenu,
	NewSysAdminTotp,
	NewInviteCode,
	NewGroupRobot,
	NewWalletUser,
	NewAppVersion,
	NewAppExplore,
	NewMerchant,
	NewMerchantTask,
	NewMerchantPaytype,
	NewMerchantPayment,
	NewAppDict,
	NewMerchantOrder,
	NewMerchantHdOrder,
	NewMerchantHmOrder,
	NewMerchantSession,
	NewMerchantMessage,
	NewNoticeLetter,
	NewNoticeTemplate,
	NewNoticeArticle,
)
