// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/gzydong/go-chat/config"
	"github.com/gzydong/go-chat/internal/apis"
	"github.com/gzydong/go-chat/internal/apis/handler"
	"github.com/gzydong/go-chat/internal/apis/handler/admin"
	"github.com/gzydong/go-chat/internal/apis/handler/admin/system"
	"github.com/gzydong/go-chat/internal/apis/handler/admin/user"
	"github.com/gzydong/go-chat/internal/apis/handler/open"
	v1_2 "github.com/gzydong/go-chat/internal/apis/handler/open/v1"
	"github.com/gzydong/go-chat/internal/apis/handler/web"
	"github.com/gzydong/go-chat/internal/apis/handler/web/v1"
	"github.com/gzydong/go-chat/internal/apis/handler/web/v1/article"
	"github.com/gzydong/go-chat/internal/apis/handler/web/v1/contact"
	"github.com/gzydong/go-chat/internal/apis/handler/web/v1/group"
	"github.com/gzydong/go-chat/internal/apis/handler/web/v1/talk"
	"github.com/gzydong/go-chat/internal/apis/router"
	"github.com/gzydong/go-chat/internal/comet"
	"github.com/gzydong/go-chat/internal/comet/consume"
	"github.com/gzydong/go-chat/internal/logic"
	"github.com/gzydong/go-chat/internal/mission"
	"github.com/gzydong/go-chat/internal/mission/cron"
	"github.com/gzydong/go-chat/internal/mission/queue"
	"github.com/gzydong/go-chat/internal/mission/temp"
	"github.com/gzydong/go-chat/internal/provider"
	"github.com/gzydong/go-chat/internal/repository/cache"
	"github.com/gzydong/go-chat/internal/repository/repo"
	"github.com/gzydong/go-chat/internal/service"
	"github.com/gzydong/go-chat/internal/service/message"
)

import (
	_ "github.com/gzydong/go-chat/internal/pkg/server"
)

// Injectors from wire.go:

func NewHttpInjector(c *config.Config) *apis.Provider {
	db := provider.NewMySQLClient(c)
	client := provider.NewRedisClient(c)
	users := repo.NewUsers(db, client)
	appVersion := repo.NewAppVersion(db)
	appExplore := repo.NewAppExplore(db)
	appModule := repo.NewAppModule(db)
	appDict := repo.NewAppDict(db)
	appNews := repo.NewAppNews(db)
	appNewsCategory := repo.NewAppNewsCategory(db)
	appNewsView := repo.NewAppNewsView(db)
	appNewsViewStorage := cache.NewAppNewsViewStorage(client)
	smsStorage := cache.NewSmsStorage(client)
	smsService := &service.SmsService{
		Storage: smsStorage,
	}
	emailStorage := cache.NewEmailStorage(client)
	emailClient := provider.NewEmailClient(c)
	emailService := &service.EmailService{
		Storage:     emailStorage,
		EmailClient: emailClient,
	}
	oAuthUsers := repo.NewOAuthUsers(db)
	userService := &service.UserService{
		UsersRepo:      users,
		OAuthUsersRepo: oAuthUsers,
	}
	templateService := &service.TemplateService{}
	common := &v1.Common{
		Config:              c,
		UsersRepo:           users,
		AppVersionRepo:      appVersion,
		AppExploreRepo:      appExplore,
		AppModuleRepo:       appModule,
		AppDictRepo:         appDict,
		AppNewsRepo:         appNews,
		AppNewsCategoryRepo: appNewsCategory,
		AppNewsViewRepo:     appNewsView,
		AppNewsViewCache:    appNewsViewStorage,
		SmsService:          smsService,
		EmailService:        emailService,
		UserService:         userService,
		EmailClient:         emailClient,
		TemplateService:     templateService,
	}
	registerLimiter := cache.NewRegisterLimiter(client)
	jwtTokenStorage := cache.NewJwtTokenStorage(client)
	redisLock := cache.NewRedisLock(client)
	robot := repo.NewRobot(db)
	source := repo.NewSource(db, client)
	articleClass := repo.NewArticleClass(db)
	articleClassService := &service.ArticleClassService{
		Source:       source,
		ArticleClass: articleClass,
	}
	iRsa := provider.NewRsa(c)
	httpClient := provider.NewHttpClient()
	iClient := provider.NewGiteeClient(httpClient)
	githubIClient := provider.NewGithubClient(httpClient)
	oAuthService := &service.OAuthService{
		OauthUsers:   oAuthUsers,
		UserSrv:      userService,
		Config:       c,
		GiteeClient:  iClient,
		GithubClient: githubIClient,
		Redis:        client,
	}
	iAesUtil := provider.NewAesUtil(c)
	captchaStorage := cache.NewCaptchaStorage(client)
	captcha := provider.NewBase64Captcha(captchaStorage)
	auth := &v1.Auth{
		Config:              c,
		Redis:               client,
		RegisterLimiter:     registerLimiter,
		JwtTokenStorage:     jwtTokenStorage,
		RedisLock:           redisLock,
		RobotRepo:           robot,
		OAuthUsersRepo:      oAuthUsers,
		UsersRepo:           users,
		SmsService:          smsService,
		EmailService:        emailService,
		UserService:         userService,
		ArticleClassService: articleClassService,
		Rsa:                 iRsa,
		OauthService:        oAuthService,
		AesUtil:             iAesUtil,
		ICaptcha:            captcha,
	}
	merchant := repo.NewMerchant(db)
	merchantTask := repo.NewMerchantTask(db)
	merchantPaytype := repo.NewMerchantPaytype(db)
	merchantPayment := repo.NewMerchantPayment(db)
	merchantOrder := repo.NewMerchantOrder(db)
	merchantHdOrder := repo.NewMerchantHdOrder(db)
	merchantHmOrder := repo.NewMerchantHmOrder(db)
	merchantSession := repo.NewMerchantSession(db)
	merchantMessage := repo.NewMerchantMessage(db)
	walletUser := repo.NewWalletUser(db)
	userClient := cache.NewUserClient(client)
	noticeTemplate := repo.NewNoticeTemplate(db, client)
	noticeLetter := repo.NewNoticeLetter(db)
	noticeArticle := repo.NewNoticeArticle(db)
	sysNotice := &logic.SysNotice{
		Redis:              client,
		NoticeLetterRepo:   noticeLetter,
		NoticeTemplateRepo: noticeTemplate,
	}
	pushMessage := &logic.PushMessage{
		Redis: client,
	}
	unreadStorage := cache.NewUnreadStorage(client)
	messageStorage := cache.NewMessageStorage(client)
	organize := repo.NewOrganize(db)
	v1User := &v1.User{
		Config:              c,
		Redis:               client,
		UsersRepo:           users,
		WalletUserRepo:      walletUser,
		MerchantRepo:        merchant,
		MerchantTaskRepo:    merchantTask,
		MerchantPaytypeRepo: merchantPaytype,
		MerchantPaymentRepo: merchantPayment,
		MerchantOrderRepo:   merchantOrder,
		MerchantHdOrderRepo: merchantHdOrder,
		MerchantHmOrderRepo: merchantHmOrder,
		MerchantSessionRepo: merchantSession,
		MerchantMessageRepo: merchantMessage,
		PushMessage:         pushMessage,
		MessageStorage:      messageStorage,
		UnreadStorage:       unreadStorage,
		UserClient:          userClient,
		NoticeTemplateRepo:  noticeTemplate,
		SysNotice:           sysNotice,
		NoticeLetterRepo:    noticeLetter,
		OrganizeRepo:        organize,
		UserService:         userService,
		SmsService:          smsService,
		EmailService:        emailService,
		Rsa:                 iRsa,
	}
	department := repo.NewDepartment(db)
	position := repo.NewPosition(db)
	v1Organize := &v1.Organize{
		DepartmentRepo: department,
		PositionRepo:   position,
		OrganizeRepo:   organize,
	}
	mentionStorage := cache.NewMentionStorage(client)
	contactRemark := cache.NewContactRemark(client)
	relation := cache.NewRelation(client)
	repoContact := repo.NewContact(db, contactRemark, relation)
	repoGroup := repo.NewGroup(db)
	groupMember := repo.NewGroupMember(db, relation)
	talkService := &service.TalkService{
		Source:          source,
		GroupMemberRepo: groupMember,
		UserRepo:        users,
		PushMessage:     pushMessage,
		MessageStorage:  messageStorage,
	}
	talkSession := repo.NewTalkSession(db)
	talkSessionService := &service.TalkSessionService{
		Source:          source,
		TalkSessionRepo: talkSession,
		GroupMemberRepo: groupMember,
		GroupRepo:       repoGroup,
	}
	groupService := &service.GroupService{
		Source:          source,
		GroupRepo:       repoGroup,
		GroupMemberRepo: groupMember,
		Relation:        relation,
		PushMessage:     pushMessage,
	}
	authService := &service.AuthService{
		OrganizeRepo:    organize,
		ContactRepo:     repoContact,
		GroupRepo:       repoGroup,
		GroupMemberRepo: groupMember,
	}
	session := &talk.Session{
		RedisLock:          redisLock,
		MessageStorage:     messageStorage,
		UnreadStorage:      unreadStorage,
		MentionStorage:     mentionStorage,
		ContactRemark:      contactRemark,
		ContactRepo:        repoContact,
		UsersRepo:          users,
		GroupRepo:          repoGroup,
		PushMessage:        pushMessage,
		TalkService:        talkService,
		TalkSessionService: talkSessionService,
		UserService:        userService,
		GroupService:       groupService,
		AuthService:        authService,
	}
	inMemoryRedEnvelopeService := service.NewInMemoryRedEnvelopeService()
	iFilesystem := provider.NewFilesystem(c)
	talkUserMessage := repo.NewTalkRecordFriend(db)
	talkGroupMessage := repo.NewTalkRecordGroup(db)
	vote := cache.NewVote(client)
	groupVote := repo.NewGroupVote(db, vote)
	talkGroupMessageDel := repo.NewTalkRecordGroupDel(db)
	talkRecordService := &service.TalkRecordService{
		Source:                source,
		TalkVoteCache:         vote,
		TalkRecordsVoteRepo:   groupVote,
		GroupMemberRepo:       groupMember,
		TalkRecordFriendRepo:  talkUserMessage,
		TalkRecordGroupRepo:   talkGroupMessage,
		TalkRecordsDeleteRepo: talkGroupMessageDel,
		TalkSessionRepo:       talkSession,
	}
	groupMemberService := &service.GroupMemberService{
		Source:          source,
		GroupMemberRepo: groupMember,
	}
	talkMessage := &talk.Message{
		TalkService:          talkService,
		AuthService:          authService,
		RedEnvelopeService:   inMemoryRedEnvelopeService,
		Filesystem:           iFilesystem,
		GroupMemberRepo:      groupMember,
		TalkRecordFriendRepo: talkUserMessage,
		TalkRecordGroupRepo:  talkGroupMessage,
		TalkRecordsService:   talkRecordService,
		GroupMemberService:   groupMemberService,
		MentionStorage:       mentionStorage,
	}
	emoticon := repo.NewEmoticon(db)
	emoticonService := &service.EmoticonService{
		Source:       source,
		EmoticonRepo: emoticon,
		Filesystem:   iFilesystem,
	}
	v1Emoticon := &v1.Emoticon{
		RedisLock:       redisLock,
		EmoticonRepo:    emoticon,
		EmoticonService: emoticonService,
		Filesystem:      iFilesystem,
	}
	fileUpload := repo.NewFileUpload(db)
	fileSplitUploadService := &service.FileSplitUploadService{
		Source:          source,
		SplitUploadRepo: fileUpload,
		Config:          c,
		FileSystem:      iFilesystem,
	}
	upload := &v1.Upload{
		Config:             c,
		Filesystem:         iFilesystem,
		SplitUploadService: fileSplitUploadService,
	}
	sts := &v1.STS{
		Config:     c,
		Filesystem: iFilesystem,
	}
	yunxinCredential := repo.NewYunxinCredential(db)
	yunxin := v1.NewYunxin(c, users, yunxinCredential)
	trtc := v1.NewTrtc(c)
	groupNotice := repo.NewGroupNotice(db)
	contactService := &service.ContactService{
		Source:      source,
		ContactRepo: repoContact,
	}
	serverStorage := cache.NewSidStorage(client)
	messageService := &message.Service{
		Source:              source,
		GroupMemberRepo:     groupMember,
		SplitUploadRepo:     fileUpload,
		TalkRecordsVoteRepo: groupVote,
		TalkSessionRepo:     talkSession,
		UsersRepo:           users,
		Filesystem:          iFilesystem,
		UnreadStorage:       unreadStorage,
		MessageStorage:      messageStorage,
		ServerStorage:       serverStorage,
		MentionStorage:      mentionStorage,
		RobotRepo:           robot,
		PushMessage:         pushMessage,
		UserClient:          userClient,
		NoticeTemplateRepo:  noticeTemplate,
	}
	groupGroup := &group.Group{
		RedisLock:          redisLock,
		Repo:               source,
		UsersRepo:          users,
		GroupRepo:          repoGroup,
		GroupMemberRepo:    groupMember,
		GroupNoticeRepo:    groupNotice,
		TalkSessionRepo:    talkSession,
		GroupService:       groupService,
		GroupMemberService: groupMemberService,
		TalkSessionService: talkSessionService,
		UserService:        userService,
		ContactService:     contactService,
		Message:            messageService,
	}
	notice := &group.Notice{
		GroupMemberRepo:    groupMember,
		GroupNoticeRepo:    groupNotice,
		GroupMemberService: groupMemberService,
		Message:            messageService,
		UsersRepo:          users,
	}
	groupApplyStorage := cache.NewGroupApplyStorage(client)
	groupApply := repo.NewGroupApply(db)
	groupApplyService := &service.GroupApplyService{
		Source:         source,
		GroupApplyRepo: groupApply,
	}
	apply := &group.Apply{
		Redis:              client,
		GroupApplyStorage:  groupApplyStorage,
		GroupRepo:          repoGroup,
		GroupApplyRepo:     groupApply,
		GroupMemberRepo:    groupMember,
		GroupApplyService:  groupApplyService,
		GroupMemberService: groupMemberService,
		GroupService:       groupService,
		PushMessage:        pushMessage,
	}
	groupVoteService := &service.GroupVoteService{
		Source:          source,
		GroupMemberRepo: groupMember,
		GroupVoteRepo:   groupVote,
	}
	vote2 := &group.Vote{
		GroupMemberRepo:  groupMember,
		GroupVoteRepo:    groupVote,
		GroupVoteService: groupVoteService,
		MessageService:   messageService,
	}
	contactContact := &contact.Contact{
		ContactRepo:     repoContact,
		UsersRepo:       users,
		OrganizeRepo:    organize,
		TalkSessionRepo: talkSession,
		ContactService:  contactService,
		UserService:     userService,
		TalkListService: talkSessionService,
		Message:         messageService,
		UserClient:      userClient,
	}
	contactApplyService := &service.ContactApplyService{
		Source:             source,
		TalkSessionRepo:    talkSession,
		PushMessage:        pushMessage,
		UsersRepo:          users,
		UserClient:         userClient,
		NoticeTemplateRepo: noticeTemplate,
	}
	v1User.TalkSessionService = talkSessionService
	talkSessionService.Message = messageService
	v1User.ContactApplyService = contactApplyService
	v1User.GroupApplyStorage = groupApplyStorage
	contactApply := &contact.Apply{
		ContactRepo:         repoContact,
		ContactApplyService: contactApplyService,
		UserService:         userService,
		ContactService:      contactService,
		MessageService:      messageService,
	}
	contactGroup := repo.NewContactGroup(db)
	contactGroupService := &service.ContactGroupService{
		Source:           source,
		ContactGroupRepo: contactGroup,
	}
	group2 := &contact.Group{
		ContactRepo:         repoContact,
		ContactGroupRepo:    contactGroup,
		ContactGroupService: contactGroupService,
		ContactService:      contactService,
	}
	articleAnnex := repo.NewArticleAnnex(db)
	repoArticle := repo.NewArticle(db)
	articleHistory := repo.NewArticleHistory(db)
	articleService := &service.ArticleService{
		Source:         source,
		ArticleRepo:    repoArticle,
		ArticleClass:   articleClass,
		ArticleHistory: articleHistory,
	}
	articleAnnexService := &service.ArticleAnnexService{
		Source:       source,
		ArticleAnnex: articleAnnex,
		FileSystem:   iFilesystem,
	}
	articleArticle := &article.Article{
		Source:              source,
		ArticleAnnexRepo:    articleAnnex,
		ArticleClassRepo:    articleClass,
		ArticleRepo:         repoArticle,
		ArticleService:      articleService,
		ArticleAnnexService: articleAnnexService,
		Filesystem:          iFilesystem,
	}
	annex := &article.Annex{
		ArticleAnnexRepo:    articleAnnex,
		ArticleAnnexService: articleAnnexService,
		Filesystem:          iFilesystem,
	}
	class := &article.Class{
		ArticleClassService: articleClassService,
	}
	articleTagService := &service.ArticleTagService{
		Source: source,
	}
	tag := &article.Tag{
		ArticleTagService: articleTagService,
	}
	publish := &talk.Publish{
		AuthService:    authService,
		MessageService: messageService,
	}
	invite := &v1.Invite{
		UsersRepo: users,
	}
	noticeHandler := &v1.Notice{
		NoticeLetterRepo:  noticeLetter,
		NoticeArticleRepo: noticeArticle,
	}
	mockKYCService := &service.MockKYCService{}
	kyc := &v1.KYC{
		KYCService: mockKYCService,
	}
	walletService := &service.WalletService{
		RedEnvelopeService: inMemoryRedEnvelopeService,
		WalletUserRepo:     walletUser,
		UsersRepo:          users,
	}
	wallet := &v1.Wallet{
		WalletService: walletService,
	}
	groupRobot := repo.NewGroupRobot(db)
	groupRobotService := &service.GroupRobotService{
		GroupRobotRepo:  groupRobot,
		GroupRepo:       repoGroup,
		GroupMemberRepo: groupMember,
		MessageService:  messageService,
	}
	v1GroupRobot := &v1.GroupRobot{
		GroupRobotService: groupRobotService,
	}
	webV1 := &web.V1{
		Common:       common,
		Auth:         auth,
		User:         v1User,
		Organize:     v1Organize,
		Talk:         session,
		TalkMessage:  talkMessage,
		Emoticon:     v1Emoticon,
		Upload:       upload,
		STS:          sts,
		Yunxin:       yunxin,
		Trtc:         trtc,
		Group:        groupGroup,
		GroupNotice:  notice,
		GroupApply:   apply,
		GroupVote:    vote2,
		Contact:      contactContact,
		ContactApply: contactApply,
		ContactGroup: group2,
		Article:      articleArticle,
		ArticleAnnex: annex,
		ArticleClass: class,
		ArticleTag:   tag,
		Message:      publish,
		Invite:       invite,
		Notice:       noticeHandler,
		KYC:          kyc,
		Wallet:       wallet,
		GroupRobot:   v1GroupRobot,
	}
	webHandler := &web.Handler{
		V1:       webV1,
		UserRepo: users,
	}
	repoAdmin := repo.NewAdmin(db)
	sysMenu := repo.NewSysMenu(db)
	adminAuth := &admin.Auth{
		Config:          c,
		AdminRepo:       repoAdmin,
		SysMenuRepo:     sysMenu,
		JwtTokenStorage: jwtTokenStorage,
		ICaptcha:        captcha,
		Rsa:             iRsa,
	}
	sysAdminTotp := repo.NewSysAdminTotp(db)
	totp := &admin.Totp{
		Rsa:              iRsa,
		AdminRepo:        repoAdmin,
		SysAdminTotpRepo: sysAdminTotp,
	}
	systemAdmin := &system.Admin{
		AdminRepo: repoAdmin,
	}
	sysRole := repo.NewSysRole(db)
	role := &system.Role{
		SysRoleRepo: sysRole,
	}
	sysResource := repo.NewSysResource(db)
	resource := &system.Resource{
		SysResourceRepo: sysResource,
	}
	menu := &system.Menu{
		SysMenuRepo: sysMenu,
	}
	userUser := &user.User{
		UserRepo: users,
	}
	adminHandler := &admin.Handler{
		Auth:      adminAuth,
		Totp:      totp,
		Admin:     systemAdmin,
		Role:      role,
		Resource:  resource,
		Menu:      menu,
		AdminRepo: repoAdmin,
		User:      userUser,
	}
	index := v1_2.NewIndex()
	v1Auth := v1_2.NewAuth(c, jwtTokenStorage)
	openV1 := &open.V1{
		Index: index,
		Auth:  v1Auth,
	}
	openHandler := &open.Handler{
		V1: openV1,
	}
	handlerHandler := &handler.Handler{
		Api:   webHandler,
		Admin: adminHandler,
		Open:  openHandler,
	}
	engine := router.NewRouter(c, handlerHandler, jwtTokenStorage)
	apisProvider := &apis.Provider{
		Config: c,
		Engine: engine,
	}
	return apisProvider
}

func NewCometInjector(c *config.Config) *comet.Provider {
	client := provider.NewRedisClient(c)
	db := provider.NewMySQLClient(c)
	organize := repo.NewOrganize(db)
	users := repo.NewUsers(db, client)
	source := repo.NewSource(db, client)
	vote := cache.NewVote(client)
	groupVote := repo.NewGroupVote(db, vote)
	relation := cache.NewRelation(client)
	groupMember := repo.NewGroupMember(db, relation)
	talkUserMessage := repo.NewTalkRecordFriend(db)
	talkGroupMessage := repo.NewTalkRecordGroup(db)
	talkGroupMessageDel := repo.NewTalkRecordGroupDel(db)
	talkSession := repo.NewTalkSession(db)
	talkRecordService := &service.TalkRecordService{
		Source:                source,
		TalkVoteCache:         vote,
		TalkRecordsVoteRepo:   groupVote,
		GroupMemberRepo:       groupMember,
		TalkRecordFriendRepo:  talkUserMessage,
		TalkRecordGroupRepo:   talkGroupMessage,
		TalkRecordsDeleteRepo: talkGroupMessageDel,
		TalkSessionRepo:       talkSession,
	}
	contactRemark := cache.NewContactRemark(client)
	repoContact := repo.NewContact(db, contactRemark, relation)
	contactService := &service.ContactService{
		Source:      source,
		ContactRepo: repoContact,
	}
	fileUpload := repo.NewFileUpload(db)
	iFilesystem := provider.NewFilesystem(c)
	unreadStorage := cache.NewUnreadStorage(client)
	messageStorage := cache.NewMessageStorage(client)
	serverStorage := cache.NewSidStorage(client)
	mentionStorage := cache.NewMentionStorage(client)
	robot := repo.NewRobot(db)
	pushMessage := &logic.PushMessage{
		Redis: client,
	}
	userClient := cache.NewUserClient(client)
	noticeTemplate := repo.NewNoticeTemplate(db, client)
	messageService := &message.Service{
		Source:              source,
		GroupMemberRepo:     groupMember,
		SplitUploadRepo:     fileUpload,
		TalkRecordsVoteRepo: groupVote,
		TalkSessionRepo:     talkSession,
		UsersRepo:           users,
		Filesystem:          iFilesystem,
		UnreadStorage:       unreadStorage,
		MessageStorage:      messageStorage,
		ServerStorage:       serverStorage,
		MentionStorage:      mentionStorage,
		RobotRepo:           robot,
		PushMessage:         pushMessage,
		UserClient:          userClient,
		NoticeTemplateRepo:  noticeTemplate,
	}
	consumeHandler := &consume.Handler{
		Config:             c,
		OrganizeRepo:       organize,
		UserRepo:           users,
		Source:             source,
		TalkRecordsService: talkRecordService,
		ContactService:     contactService,
		MessageService:     messageService,
		GroupMemberRepo:    groupMember,
	}
	subscribe := &comet.Subscribe{
		Redis:   client,
		Handler: consumeHandler,
	}
	cometHandler := &comet.Handler{
		UserClient:  userClient,
		PushMessage: pushMessage,
	}
	heartbeat := &comet.Heartbeat{
		ServerStorage: serverStorage,
		Redis:         client,
	}
	userJwtAuthorize := provider.NewWebUserJwtAuthorize(c)
	server := &comet.Server{
		Config:    c,
		Subscribe: subscribe,
		Handler:   cometHandler,
		Heartbeat: heartbeat,
		Authorize: userJwtAuthorize,
		Redis:     client,
	}
	cometProvider := &comet.Provider{
		Server: server,
	}
	return cometProvider
}

func NewCronInjector(c *config.Config) *mission.CronProvider {
	db := provider.NewMySQLClient(c)
	iFilesystem := provider.NewFilesystem(c)
	clearArticle := &cron.ClearArticle{
		DB:         db,
		Filesystem: iFilesystem,
	}
	clearTmpFile := &cron.ClearTmpFile{
		DB:         db,
		Filesystem: iFilesystem,
	}
	inMemoryRedEnvelopeService := service.NewInMemoryRedEnvelopeService()
	walletUser := repo.NewWalletUser(db)
	client := provider.NewRedisClient(c)
	users := repo.NewUsers(db, client)
	walletService := &service.WalletService{
		RedEnvelopeService: inMemoryRedEnvelopeService,
		WalletUserRepo:     walletUser,
		UsersRepo:          users,
	}
	expireRedEnvelope := &cron.ExpireRedEnvelope{
		WalletService:      walletService,
		RedEnvelopeService: inMemoryRedEnvelopeService,
	}
	merchantOrder := repo.NewMerchantOrder(db)
	expireMerchantOrder := &cron.ExpireMerchantOrder{
		MerchantOrderRepo: merchantOrder,
	}
	talkUserMessage := repo.NewTalkRecordFriend(db)
	talkSession := repo.NewTalkSession(db)
	messageStorage := cache.NewMessageStorage(client)
	expireTalkUserMessage := &cron.ExpireTalkUserMessage{
		TalkUserMessageRepo: talkUserMessage,
		TalkSessionRepo:     talkSession,
		MessageStorage:      messageStorage,
	}
	crontab := &cron.Crontab{
		ClearArticle:          clearArticle,
		ClearTmpFile:          clearTmpFile,
		ExpireRedEnvelope:     expireRedEnvelope,
		ExpireMerchantOrder:   expireMerchantOrder,
		ExpireTalkUserMessage: expireTalkUserMessage,
	}
	cronProvider := &mission.CronProvider{
		Config:  c,
		Crontab: crontab,
	}
	return cronProvider
}

func NewQueueInjector(c *config.Config) *mission.QueueProvider {
	db := provider.NewMySQLClient(c)
	robot := repo.NewRobot(db)
	client := provider.NewRedisClient(c)
	source := repo.NewSource(db, client)
	httpClient := provider.NewHttpClient()
	ipaddressClient := provider.NewIpAddressClient(httpClient)
	ipAddressService := &service.IpAddressService{
		Source:          source,
		Config:          c,
		IpAddressClient: ipaddressClient,
	}
	talkSession := repo.NewTalkSession(db)
	relation := cache.NewRelation(client)
	groupMember := repo.NewGroupMember(db, relation)
	repoGroup := repo.NewGroup(db)
	talkSessionService := &service.TalkSessionService{
		Source:          source,
		TalkSessionRepo: talkSession,
		GroupMemberRepo: groupMember,
		GroupRepo:       repoGroup,
	}
	fileUpload := repo.NewFileUpload(db)
	vote := cache.NewVote(client)
	groupVote := repo.NewGroupVote(db, vote)
	users := repo.NewUsers(db, client)
	iFilesystem := provider.NewFilesystem(c)
	unreadStorage := cache.NewUnreadStorage(client)
	messageStorage := cache.NewMessageStorage(client)
	serverStorage := cache.NewSidStorage(client)
	mentionStorage := cache.NewMentionStorage(client)
	pushMessage := &logic.PushMessage{
		Redis: client,
	}
	userClient := cache.NewUserClient(client)
	noticeTemplate := repo.NewNoticeTemplate(db, client)
	messageService := &message.Service{
		Source:              source,
		GroupMemberRepo:     groupMember,
		SplitUploadRepo:     fileUpload,
		TalkRecordsVoteRepo: groupVote,
		TalkSessionRepo:     talkSession,
		UsersRepo:           users,
		Filesystem:          iFilesystem,
		UnreadStorage:       unreadStorage,
		MessageStorage:      messageStorage,
		ServerStorage:       serverStorage,
		MentionStorage:      mentionStorage,
		RobotRepo:           robot,
		PushMessage:         pushMessage,
		UserClient:          userClient,
		NoticeTemplateRepo:  noticeTemplate,
	}
	userLoginConsumer := &queue.UserLoginConsumer{
		RobotRepo:          robot,
		IpAddressService:   ipAddressService,
		TalkSessionService: talkSessionService,
		Message:            messageService,
	}
	sysNoticeConsumer := &queue.SysNoticeConsumer{
		UsersRepo:   users,
		UserClient:  userClient,
		PushMessage: pushMessage,
	}
	consumers := &queue.Consumers{
		UserLoginConsumer: userLoginConsumer,
		SysNoticeConsumer: sysNoticeConsumer,
	}
	queueProvider := &mission.QueueProvider{
		Consumers: consumers,
		Redis:     client,
	}
	return queueProvider
}

func NewTempInjector(c *config.Config) *mission.TempProvider {
	db := provider.NewMySQLClient(c)
	client := provider.NewRedisClient(c)
	users := repo.NewUsers(db, client)
	testCommand := temp.TestCommand{
		UserRepo: users,
	}
	tempProvider := &mission.TempProvider{
		TestJob: testCommand,
	}
	return tempProvider
}

func NewMigrateInjector(c *config.Config) *mission.MigrateProvider {
	db := provider.NewMySQLClient(c)
	migrateProvider := &mission.MigrateProvider{
		Config: c,
		DB:     db,
	}
	return migrateProvider
}

// wire.go:

var providerSet = wire.NewSet(provider.ProviderSet, cache.ProviderSet, repo.ProviderSet, logic.ProviderSet, service.ProviderSet)
